"use client";
import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Check, Compass, Unlock } from 'lucide-react';
import { type LearningRoadmap, roadmapNodes } from '@/lib/roadmaps';
import { type RoadmapGuide } from '@/lib/roadmap-guides';
import './roadmap-studio.css';

export default function RoadmapShowcase({ roadmaps, guides: roadmapGuides }: { roadmaps: LearningRoadmap[]; guides: Record<string, RoadmapGuide> }) {
  const [slug, setSlug] = useState(roadmaps[0]?.slug ?? '');
  const roadmap = roadmaps.find(item => item.slug === slug) ?? roadmaps[0];
  if (!roadmap) return null;
  const guide = roadmapGuides[roadmap.slug];
  return <section id="roadmaps" className="roadmap-studio"><div className="rs-container"><div className="rs-hero"><div className="rs-copy"><span className="rs-eyebrow"><Compass size={16}/> DOLPHINX / BẢN ĐỒ HỌC TẬP</span><h2>Đừng học lan man.<br/>Hãy có một <em>đường đi.</em></h2><p>Từ “mình nên học gì?” đến sản phẩm đầu tiên.<br/>Chọn một hướng, khám phá từng chặng và bắt đầu từ nơi phù hợp với bạn.</p><a className="rs-primary" href="#roadmap-explorer">Tìm đường đi của bạn <ArrowUpRight size={18}/></a><span className="rs-open"><Unlock size={14}/> Mở hoàn toàn · Không cần đăng nhập</span></div><div className="rs-art"><Image src="/brand/roadmap-navigator-v1.png" alt="Cá heo DolphinX cầm bản đồ, khám phá các đảo kiến thức lập trình" width={1536} height={1024} sizes="(max-width:800px) 100vw, 50vw"/><span className="rs-art-label"><Compass size={16}/><span>Mỗi chặng nhỏ.<br/><strong>Một bước tiến xa.</strong></span></span></div></div>
    <div id="roadmap-explorer" className="rs-explorer"><div className="rs-explorer-heading"><div><span className="rs-eyebrow">01 / CHỌN HƯỚNG ĐI</span><h3>Bạn muốn tạo ra điều gì?</h3></div><Link href="/roadmaps">Tất cả lộ trình <ArrowUpRight size={16}/></Link></div><div className="rs-choices" aria-label="Chọn lộ trình xem trước">{roadmaps.map(item=><button key={item.slug} onClick={()=>setSlug(item.slug)} aria-pressed={roadmap.slug===item.slug} aria-controls="roadmap-preview"><span>{item.symbol}</span><strong>{item.title}</strong><small>{item.slug === 'frontend' ? 'Giao diện & trải nghiệm' : item.slug === 'backend' ? 'API & hệ thống' : item.slug === 'python' ? 'Code & tự động hóa' : 'Truy vấn & báo cáo'}</small><ArrowUpRight size={16}/></button>)}</div>
    <div className="rs-preview" id="roadmap-preview"><div className="rs-route"><div className="rs-route-heading"><span className="rs-eyebrow">02 / KHÁM PHÁ CÁC CHẶNG</span><span>{roadmap.stages.length} chặng · {roadmapNodes(roadmap).length} chủ đề</span></div><h3>{roadmap.title}</h3><p>{guide.audience}</p><ol className="rs-route-steps">{guide.stages.slice(0,3).map((stage,index)=><li key={stage.label}><Link href={`/roadmaps/${roadmap.slug}#stage-${index}`}><span>{String(index+1).padStart(2,'0')}</span><div><strong>{stage.label}</strong><small>{roadmap.stages[index].nodes.map(node=>node.title).join(' · ')}</small></div><ArrowUpRight size={15}/></Link></li>)}</ol><details className="rs-more-stages" key={slug}><summary>Xem thêm {Math.max(0, guide.stages.length - 3)} chặng tiếp theo</summary><ol className="rs-route-steps" start={4}>{guide.stages.slice(3).map((stage,index)=><li key={stage.label}><Link href={`/roadmaps/${roadmap.slug}#stage-${index+3}`}><span>{String(index+4).padStart(2,'0')}</span><div><strong>{stage.label}</strong><small>{roadmap.stages[index+3].nodes.map(node=>node.title).join(' · ')}</small></div><ArrowUpRight size={15}/></Link></li>)}</ol></details></div><aside className="rs-destination"><span className="rs-eyebrow">03 / ĐÍCH ĐẾN CỦA BẠN</span><div className="rs-destination-symbol">{roadmap.symbol}</div><h3>{guide.project}</h3><ul>{guide.deliverables.map(item=><li key={item}><Check size={17}/>{item}</li>)}</ul><div className="rs-prerequisite"><strong>Trước khi bắt đầu</strong><p>{guide.prerequisite}</p></div><Link className="rs-primary" href={`/roadmaps/${roadmap.slug}`}>Mở bản đồ chi tiết <ArrowUpRight size={18}/></Link><small>Đọc tài liệu và bài thực hành miễn phí.<br/>Chỉ đăng nhập khi muốn lưu tiến độ.</small></aside></div></div><p className="rs-footnote">Không có tốc độ học “đúng” cho tất cả. Bạn có thể quay lại bất kỳ chặng nào, bất kỳ lúc nào.</p></div></section>;
}
