import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, Check, Code2, Map, Play, BookOpen } from "lucide-react";
import RoadmapShowcase from "./roadmaps/roadmap-showcase";

import { getRoadmapContent } from "@/lib/managed-content";
export async function RoadmapDiscovery() { return <RoadmapShowcase {...await getRoadmapContent()}/>; }

export function DashboardExperience() {
  return <section className="lx-experience" id="approach"><div className="bp-container lx-split"><div><span className="bp-eyebrow">KHÔNG GIAN HỌC DOLPHINX</span><h2>Không chỉ xem.<br/>Hãy <em>tự tay làm.</em></h2><p>Khám phá khóa học, luyện bài và theo dõi lộ trình trong cùng một không gian.</p><ol className="lx-steps"><li><span>01</span><div><h3>Vào xem trước</h3><p>Mở dashboard ngay, chưa cần đăng nhập.</p></div></li><li><span>02</span><div><h3>Chọn điều muốn học</h3><p>Khám phá khóa học hoặc tìm hướng đi qua roadmap.</p></div></li><li><span>03</span><div><h3>Đăng nhập để bắt đầu</h3><p>Lưu tiến độ riêng; bài học áp dụng quyền truy cập của từng khóa.</p></div></li></ol><Link className="bp-button" href="/dashboard">Trải nghiệm dashboard <ArrowUpRight/></Link></div>
    <div className="lx-preview" aria-label="Minh họa các chức năng dashboard"><div className="lx-preview-bar"><span>DolphinX / Không gian học</span><small>MINH HỌA GIAO DIỆN</small></div><div className="lx-preview-body"><span className="bp-eyebrow">HÔM NAY BẠN MUỐN HỌC GÌ?</span><h3>Mỗi bước nhỏ đều có giá trị.</h3><div className="lx-preview-course"><Image src="/brand/course-coding-mascot-v3.png" alt="Cá heo DolphinX đang thực hành lập trình" width={1672} height={941} sizes="(max-width:700px) 90vw, 40vw"/><div><BookOpen/><span><strong>Khám phá thư viện</strong><small>Chọn khóa phù hợp với nền tảng của bạn</small></span></div></div><div className="lx-preview-tiles"><Link href="/dashboard#practice"><Code2/><strong>Luyện tập</strong><small>Thử sức với bài lập trình</small><ArrowUpRight/></Link><Link href="/roadmaps"><Map/><strong>Lộ trình</strong><small>Theo dõi từng chủ đề</small><ArrowUpRight/></Link></div><p><Check/> Tiến độ gắn với tài khoản sau khi đăng nhập</p></div></div></div></section>;
}

export function MentoringSummary() {
  return <section className="bp-container lx-section lx-split" id="mentoring"><div className="lx-mentor-art"><Image src="/brand/bright-mentor.png" alt="Ảnh AI minh họa buổi học cùng mentor, không phải hồ sơ nhân sự" width={1448} height={1086} sizes="(max-width:700px) 90vw, 45vw"/><span>ẢNH AI MINH HỌA · KHÔNG PHẢI HỒ SƠ MENTOR</span></div><div><span className="bp-eyebrow">KHI BẠN CẦN NGƯỜI ĐỒNG HÀNH</span><h2>Một mục tiêu.<br/>Một người <em>cùng gỡ khó.</em></h2><p>Học online 1:1 để làm rõ kiến thức, review code và hoàn thiện dự án theo nhu cầu của bạn.</p><ul className="lx-mentor-points"><li><Check/> Trao đổi nền tảng và mục tiêu trước khi học</li><li><Check/> Thống nhất nội dung, lịch học và học phí</li><li><Check/> Thực hành và hỏi đáp trong buổi học</li></ul><Link className="bp-button" href="/consultation">Tư vấn lộ trình 1:1 <ArrowUpRight/></Link><p className="lx-note"><Play size={15}/> Thông tin mentor và lịch nhận học được xác nhận khi tư vấn.</p></div></section>;
}
