import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, BookOpen, Code2, Compass, Users, Check, MessagesSquare, Trophy } from 'lucide-react';
import EduFooter from './edu-footer';
import EduNavbar from './edu-navbar';
import EduMotion from './edu-motion';
import EduHomeEditorial, { EduHomeJournal } from './edu-home-editorial';
import EduPrograms from './edu-programs';
import './edu-typography.css';
import { RoadmapDiscovery } from './landing-experience';
import './edu-landing.css';
import './edu-photo-cta.css';
import './edu-home-hero.css';
import './edu-home-faq.css';
export const dynamic = 'force-dynamic';
const questions = [
 ['Chưa biết lập trình, mình nên bắt đầu từ đâu?', 'Bạn có thể xem lộ trình công khai hoặc bắt đầu với khóa lập trình kéo thả. Nếu chưa chắc hướng đi, hãy gửi mục tiêu để được tư vấn trước khi chọn khóa.'],
 ['Mình có thể vào xem trước khi đăng ký không?', 'Có. Dashboard, thông tin khóa học và lộ trình đều có thể xem trước. Khi bắt đầu làm bài hoặc lưu tiến độ, bạn sẽ được yêu cầu đăng nhập.'],
 ['Video hiện tại đã là bài giảng chính thức chưa?', 'Một số khóa đang dùng video demo để minh họa trình phát. Các bài này được ghi nhãn rõ ràng; giáo án và bài thực hành có sẵn để bạn xem trước.'],
 ['Học online 1:1 được tổ chức thế nào?', 'Đội ngũ trao đổi nền tảng, mục tiêu, lịch học và học phí với bạn trước khi xác nhận. Nội dung có thể tập trung vào kiến thức nền, review code hoặc dự án cá nhân.'],
 ['Đăng ký tài khoản có mở toàn bộ khóa học không?', 'Không. Tài khoản giúp lưu tiến độ cá nhân. Với khóa cần quyền truy cập, bạn sử dụng mã hoặc quyền được đội ngũ cấp; đăng ký khóa không tự thực hiện thanh toán.'],
];
const features=[
 {Icon:BookOpen,title:'Hiểu từ gốc',text:'Đi qua từng khái niệm với giáo án, ví dụ và bài thực hành. Xem lại khi cần, học theo tốc độ của mình.'},
 {Icon:Code2,title:'Học bằng cách làm',text:'Thử viết lời giải ngay trong trình soạn code, chạy test và nhìn thấy điều cần cải thiện.'},
 {Icon:Users,title:'Có người cùng gỡ khó',text:'Trao đổi với cộng đồng hoặc chọn học online 1:1 theo mục tiêu và nền tảng của bạn.'},
];
export default function Home(){return <div className="edu edu-public-type"><EduNavbar/><EduMotion><main id="main-content">
 <section className="edu-hero"><div className="edu-container"><h1>Khơi mở tiềm năng.<br/>Tự tin <span>tạo điều mới.</span></h1><div className="edu-hero-bottom"><p>Học lập trình theo cách của bạn — từ nền tảng đầu tiên<br className="edu-desktop-break"/> đến sản phẩm thực tế, luôn có một hướng đi rõ ràng.</p><div><Link className="edu-button" href="/dashboard">Bắt đầu hành trình <ArrowUpRight size={19}/></Link><a className="edu-link" href="#programs">Khám phá chương trình</a></div></div></div></section>
 <div className="edu-values edu-container">{[{Icon:BookOpen,title:'Học theo nhịp riêng',sub:'Video & giáo án'},{Icon:Code2,title:'Thực hành từ sớm',sub:'Code & dự án'},{Icon:Compass,title:'Biết bước tiếp theo',sub:'Lộ trình rõ ràng'},{Icon:Users,title:'Không học một mình',sub:'Mentor & cộng đồng'}].map(({Icon,title,sub})=><div key={title}><span className="edu-icon"><Icon size={24}/></span><span><strong>{title}</strong><small>{sub}</small></span></div>)}</div>
 <section data-reveal className="edu-section edu-container" id="about"><div className="edu-section-head"><div><span className="edu-label">01 / VỀ DOLPHINX EDU</span><h2>Một điểm bắt đầu.<br/><span>Nhiều khả năng phía trước.</span></h2></div><div><p>Không cần biết mọi thứ để bắt đầu. DolphinX Edu kết nối kiến thức, thực hành và người đồng hành để bạn đi từ “chưa biết” đến “tự làm được”.</p><a href="#approach" className="edu-link">Cách chúng mình học <ArrowUpRight size={18}/></a></div></div><div className="edu-feature-grid">{features.map(({Icon,title,text})=><article key={title}><span className="edu-icon"><Icon size={28}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section data-reveal className="edu-programs edu-section" id="programs"><div className="edu-container"><div className="edu-section-head"><div><span className="edu-label">02 / CHƯƠNG TRÌNH HỌC</span><h2>Chọn điều bạn muốn.<br/><span>Bắt đầu từ hôm nay.</span></h2></div><p>Từ tư duy lập trình đến xây dựng ứng dụng.<br/>Chọn một nền tảng phù hợp, rồi đi từng bước.</p></div><EduPrograms/></div></section>
 <RoadmapDiscovery/>
 <section data-reveal className="edu-section edu-container edu-approach" id="approach"><div><span className="edu-label">03 / TỪ HIỂU ĐẾN LÀM ĐƯỢC</span><h2>Kiến thức chỉ thật sự<br/><span>của bạn khi thực hành.</span></h2><p>Không gian học tập kết nối bài giảng, bài tập và tiến độ. Mỗi lời giải là một cơ hội để hiểu sâu hơn.</p><Link href="/dashboard#practice" className="edu-button">Vào phòng luyện code <ArrowUpRight size={18}/></Link></div><div className="edu-code-art" aria-label="Minh họa bài tập lập trình"><div><span/><span/><span/><small>YOUR NEXT SMALL WIN / solve.js</small></div><pre><span>{'// Một bước nhỏ mỗi ngày'}</span>{'\n'}<b>function</b>{' solve(ideas) {\n  const skills = ideas.map(learn);\n  return build(skills);\n}'}</pre><footer><Check size={18}/><span>Đọc đề · Viết code · Chạy thử</span><Code2 size={24}/></footer><p>Minh họa giao diện · Không phải kết quả chấm thực tế</p></div></section>
 <section data-reveal className="edu-mentor" id="mentoring"><div className="edu-container edu-mentor-grid"><div className="edu-mentor-photo"><Image src="/brand/company/presentation-white-v1.png" alt="Ảnh trình bày dự án từ bộ ảnh đội ngũ; trang phục được chỉnh bằng AI" width={1448} height={1086} sizes="(max-width:800px) 90vw, 45vw"/><span>ẢNH ĐỘI NGŨ · ĐỒNG PHỤC CHỈNH BẰNG AI</span></div><div><span className="edu-label">04 / MENTOR ONLINE 1:1</span><h2>Mục tiêu của bạn.<br/><span>Lộ trình của riêng bạn.</span></h2><p>Một người đồng hành để hỏi những điều chưa rõ, cùng review code và tháo gỡ vướng mắc trong dự án.</p><ul>{['Trao đổi nền tảng và mục tiêu trước khi học','Thống nhất nội dung, lịch học và học phí','Thực hành, hỏi đáp và review trực tiếp'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><Link href="/consultation" className="edu-button">Trao đổi cùng đội ngũ <ArrowUpRight size={18}/></Link><small>Thông tin mentor và lịch nhận học được xác nhận khi tư vấn.</small></div></div></section>
 <section data-reveal className="edu-section edu-container" id="community"><div className="edu-section-head"><div><span className="edu-label">05 / CÙNG NHAU TIẾN BỘ</span><h2>Hành trình học tập.<br/><span>Không chỉ một mình.</span></h2></div><p>Chia sẻ điều vừa học, thử sức với thử thách mới<br/>và biến những ý tưởng nhỏ thành sản phẩm.</p></div><div className="edu-community-grid">{[{Icon:MessagesSquare,title:'Cộng đồng học tập',text:'Đặt câu hỏi, chia sẻ cách làm và trao đổi cùng những người đang học như bạn.',href:'/community',cta:'Tham gia trao đổi'},{Icon:Trophy,title:'Cuộc thi lập trình',text:'Khám phá các cuộc thi được công bố, đọc thể lệ và luyện kỹ năng giải quyết vấn đề.',href:'/contests',cta:'Khám phá cuộc thi'},{Icon:BookOpen,title:'Thư viện thực hành',text:'Tìm tài liệu và bài hướng dẫn để ôn lại kiến thức, làm thử rồi tự đánh giá.',href:'/resources',cta:'Mở thư viện'}].map(({Icon,title,text,href,cta})=><Link href={href} key={title}><span className="edu-icon"><Icon size={25}/></span><h3>{title}</h3><p>{text}</p><span className="edu-link">{cta}<ArrowUpRight size={18}/></span></Link>)}</div></section>
 <EduHomeEditorial/>
 <section className="edu-faq edu-home-faq edu-section edu-container"><div><span className="edu-label">GIẢI ĐÁP TRƯỚC KHI BẮT ĐẦU</span><h2>Bạn hỏi.<br/><span>Chúng mình trả lời.</span></h2><Link className="edu-link" href="/consultation">Vẫn còn thắc mắc? <ArrowUpRight size={18}/></Link></div><div>{questions.map(([q,a],index)=><details key={q} name="home-faq" open={index===0}><summary>{q}<ArrowUpRight size={24} aria-hidden="true"/></summary><p>{a}</p></details>)}</div></section>
 <section className="edu-cta edu-photo-cta" aria-labelledby="next-chapter-heading"><Image className="edu-photo-cta-image" src="/brand/company/presentation-white-v1.png" alt="Người đại diện đang thuyết trình; đồng phục DolphinX trắng được chỉnh bằng AI từ ảnh đội ngũ" width={1536} height={1024} sizes="100vw"/><div className="edu-container"><div className="edu-photo-cta-copy"><span className="edu-label">CHƯƠNG TIẾP THEO BẮT ĐẦU TỪ ĐÂY</span><h2 id="next-chapter-heading">Điều mới tiếp theo,<br/>bắt đầu từ <em>bạn.</em></h2><p>Cho sự tò mò một hướng đi. Cho ý tưởng một cơ hội thành hình.</p><Link href="/dashboard" className="edu-button">Bắt đầu cùng DolphinX Edu <ArrowUpRight size={20}/></Link></div></div><small className="edu-photo-cta-note">Ảnh đội ngũ · Đồng phục chỉnh bằng AI</small></section>
 <EduHomeJournal/>
 </main></EduMotion><EduFooter/></div>;}
