"use client";
import { useState } from "react";
import Link from "next/link";
import { type PracticeResource, resourceSources } from "@/lib/resources";
import "./resources.css";
import "./resource-detail.css";
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/đ/g, "d").toLowerCase();
export default function ResourceExplorer({ practiceResources, blockCount }: { practiceResources: PracticeResource[]; blockCount: number }) {
  const [query, setQuery] = useState(""), [topic, setTopic] = useState("Tất cả"), [level, setLevel] = useState("Tất cả");
  const topics = [...new Set(practiceResources.map(item => item.topic))];
  const items = practiceResources.filter(item => (topic === "Tất cả" || item.topic === topic) && (level === "Tất cả" || item.level === level) && normalize(`${item.title} ${item.description} ${item.kind} ${item.topic}`).includes(normalize(query.trim())));
  return <main className="resources-page"><header className="resources-hero"><span>LEARN · BUILD · DEBUG</span><h1>Đọc để hiểu.<br/>Thực hành để nhớ.</h1><p>Tài liệu chọn lọc và những thử thách nhỏ để biến kiến thức thành sản phẩm. Chọn một bài, mở editor của bạn và bắt đầu.</p><Link href="/dashboard#practice">Đến kho bài có máy chấm →</Link></header><section className="resource-block-banner"><span>THỰC HÀNH TƯƠNG TÁC</span><h2>Kéo thả khối lệnh. Cá heo làm theo bạn.</h2><p>{blockCount} thử thách từ di chuyển đến vòng lặp và điều kiện. Chạy thử miễn phí, nộp bài để chấm điểm và lưu kỷ lục.</p><Link className="resource-open-link" href="/resources/blocks">Mở phòng khối lệnh →</Link><Link className="resource-open-link" href="/courses/scratch-blocks">Xem khóa học kéo thả →</Link></section><section><h2>Tài liệu nền tảng</h2><p className="resources-note">Nguồn chính thức · Miễn phí truy cập · Nội dung tiếng Anh</p><div className="resource-sources">{resourceSources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer"><span>{source.topic}</span><h3>{source.title} ↗</h3><p>{source.description}</p></a>)}</div></section><section><div className="resource-heading"><div><h2>Phòng thực hành</h2><p>Mini project, debug, SQL và thuật toán. Thời gian là ước tính; làm trong môi trường riêng, tự đối chiếu tiêu chí. Không chấm tự động hoặc cộng XP tại đây.</p></div></div><div className="resource-filters"><label>Tìm nội dung<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Ví dụ: giỏ hàng, Python…"/></label><label>Chủ đề<select value={topic} onChange={event => setTopic(event.target.value)}><option>Tất cả</option>{topics.map(t => <option key={t}>{t}</option>)}</select></label><label>Trình độ<select value={level} onChange={event => setLevel(event.target.value)}><option>Tất cả</option><option>Cơ bản</option><option>Trung cấp</option></select></label><button onClick={() => { setQuery(""); setTopic("Tất cả"); setLevel("Tất cả"); }}>Xóa bộ lọc</button></div><p role="status" className="resources-note">{items.length} bài thực hành phù hợp</p><div className="practice-resources">{items.map(item => <article key={item.id}><div className="resource-tags"><span>{item.topic}</span><span>{item.kind}</span><span>{item.level}</span></div><h3>{item.title}</h3><p>{item.description}</p><small>Khoảng {item.minutes} phút · Tự luyện</small><Link className="resource-open-link" href={`/resources/${item.id}`}>Xem bài thực hành →</Link></article>)}</div>{!items.length && <div className="resources-empty"><h3>Chưa có bài phù hợp</h3><p>Thử chủ đề khác hoặc xóa bộ lọc.</p></div>}</section></main>;
}
