import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Code2, Users, Lightbulb } from 'lucide-react';
import EduPublicShell, { EditorialHero } from '../edu-public-shell';
import EduStudyOptions from '../edu-study-options';

export const metadata={title:'Về DolphinX Edu — Con người, công nghệ và hành trình học tập'};
export default function AboutPage(){return <EduPublicShell>
<EditorialHero groupPortrait label="VỀ DOLPHINX EDU" title="Cùng tạo nên những giá trị thật." image="/brand/company/presentation-original.png" alt="Ảnh gốc thành viên đội ngũ đang thuyết trình"/>
  <section className="edu-container ed-story" data-reveal><span className="edu-label">CÂU CHUYỆN CỦA CHÚNG MÌNH</span><div><p className="ed-lead">Một dòng code có thể là điểm bắt đầu. Một người đồng hành có thể giúp bạn đi xa hơn.</p><p>DolphinX Edu xây dựng một không gian học lập trình kết nối kiến thức, thực hành và cộng đồng. Bạn có thể khám phá lộ trình trước, học từng bài theo nhịp riêng và áp dụng điều vừa học vào một sản phẩm cụ thể.</p><p>Tinh thần của DolphinX nằm trong cách chúng mình làm việc: hiểu vấn đề, thử nghiệm, chia sẻ và cải thiện. Từ bài tập đầu tiên đến dự án cá nhân, mỗi bước tiến đều có ý nghĩa.</p></div></section>
  <section className="ed-welcome"><div className="edu-container ed-split" data-reveal><div className="ed-documentary"><Image src="/brand/company/presentation-original.png" alt="Khoảnh khắc thuyết trình trong ảnh gốc do đội ngũ cung cấp" width={2048} height={1365} sizes="(max-width:800px) 90vw, 45vw"/><small>Ảnh gốc do đội ngũ cung cấp</small></div><div><span className="ed-quote">“</span><h2>Học để hiểu.<br/>Làm để trưởng thành.</h2><p>Chúng mình muốn việc học không dừng lại ở một video đã xem. Đó còn là câu hỏi bạn dám đặt, lỗi bạn tự tìm ra và sản phẩm bạn có thể giải thích bằng chính lời của mình.</p><Link href="/consultation" className="edu-link">Trao đổi về mục tiêu của bạn <ArrowUpRight size={19}/></Link></div></div></section>
  <section className="edu-section edu-container" data-reveal><div className="edu-section-head"><div><span className="edu-label">BẮT ĐẦU THẾ NÀO?</span><h2>Bốn bước nhỏ.<br/>Một hành trình của bạn.</h2></div><p>Khám phá trước khi quyết định. Chọn cách học phù hợp với nền tảng, quỹ thời gian và mục tiêu.</p></div><div className="ed-steps">{[['Khám phá','Xem lộ trình, chủ đề và nội dung khóa học công khai.','/roadmaps'],['Chọn hướng đi','Tìm chương trình phù hợp hoặc trao đổi về nhu cầu học 1:1.','/courses'],['Bắt đầu học','Tạo tài khoản khi cần lưu tiến độ và đăng ký quyền học phù hợp.','/dashboard'],['Thực hành đều đặn','Luyện bài tập, chia sẻ vướng mắc và tiếp tục cải thiện.','/community']].map(([title,text,href],i)=><Link href={href} key={title}><span>0{i+1}<ArrowUpRight size={21}/></span><h3>{title}</h3><p>{text}</p></Link>)}</div></section>
  <section className="ed-values"><div className="edu-container edu-feature-grid" data-reveal>{[{Icon:Lightbulb,title:'Tò mò để khám phá',text:'Bắt đầu từ câu hỏi. Hiểu lý do phía sau từng công cụ và từng lời giải.'},{Icon:Users,title:'Cùng nhau tiến bộ',text:'Lắng nghe góc nhìn khác, chia sẻ điều đã biết và học từ phản hồi.'},{Icon:Code2,title:'Tạo ra giá trị thật',text:'Đưa kiến thức vào thực hành, kiểm thử kết quả và giải quyết vấn đề cụ thể.'}].map(({Icon,title,text})=><article key={title}><Icon size={35}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="edu-section edu-container" data-reveal><div className="edu-section-head"><div><span className="edu-label">CON NGƯỜI DOLPHINX</span><h2>Mỗi cá tính.<br/>Một tinh thần chung.</h2></div><p>Những gương mặt phía sau DolphinX — cùng chia sẻ kiến thức, lắng nghe và tạo nên một không gian học tập gần gũi.</p></div><div className="ed-portraits"><figure><Image src="/brand/company/representative-navy-v1.png" alt="Gương mặt đại diện DolphinX trong phiên bản đồng phục navy" width={1024} height={1536} sizes="(max-width:600px) 90vw, 40vw"/><figcaption>Cùng chia sẻ kiến thức</figcaption></figure><figure><Image src="/brand/company/representative-white-v1.png" alt="Gương mặt đại diện DolphinX đeo kính trong phiên bản đồng phục trắng" width={1024} height={1536} sizes="(max-width:600px) 90vw, 40vw"/><figcaption>Cùng mở rộng góc nhìn</figcaption></figure></div><p className="ed-image-note">Chân dung từ ảnh gốc của đội ngũ; trang phục được chỉnh bằng AI.</p></section>
  <EduStudyOptions/>
</EduPublicShell>;}
