import Link from 'next/link';
import { hubDb,pageNumber,dateLabel } from '@/lib/hub';
import { getSessionUser } from '@/lib/user-auth';
import AcademyForm from '@/app/academy/form';
import { communityAction } from '@/app/community-actions';
import PublicAccount from '@/app/public-account';
export const metadata={title:'Cộng đồng lập trình | DolphinX'};
export default async function Page({searchParams}:{searchParams:Promise<{page?:string;category?:string;mine?:string}>}){
 const query=await searchParams;const page=pageNumber(query.page),user=await getSessionUser(),db=await hubDb();const mine=query.mine==='1'&&!!user;
 const category=['Hỏi đáp','Chia sẻ','Dự án'].includes(query.category??'')?query.category:undefined;
 const filter={...(mine?{userId:user!.id}:{status:'published'}),...(category?{category}:{})};
 const posts=await db.collection('community_posts').find(filter,{projection:{title:1,body:1,authorName:1,category:1,status:1,createdAt:1}}).sort({createdAt:-1}).skip((page-1)*20).limit(21).toArray();
 const href=(n:number)=>`/community?${new URLSearchParams({page:String(n),...(category?{category}:{}),...(mine?{mine:'1'}:{})})}`;
 return <main className="hub-main"><section className="hub-hero"><span className="hub-eyebrow">DOLPHINX COMMUNITY / HỌC KHÔNG MỘT MÌNH</span><h1>Một câu hỏi nhỏ.<br/><em>Nhiều góc nhìn mới.</em></h1><p>Hỏi đáp lập trình, chia sẻ điều vừa học và giới thiệu dự án bạn đang xây.</p><div className="hub-chips"><span>Hỏi có ngữ cảnh</span><span>Góp ý tử tế</span><span>Không chia sẻ bí mật</span></div></section><div className="hub-grid"><section><nav className="hub-tabs" aria-label="Lọc bài viết"><Link href="/community">Tất cả</Link>{['Hỏi đáp','Chia sẻ','Dự án'].map(c=><Link key={c} href={`/community?category=${encodeURIComponent(c)}`}>{c}</Link>)}{user&&<Link href="/community?mine=1">Bài của tôi</Link>}</nav><h2>{mine?'Bài viết của bạn':category??'Bảng tin cộng đồng'}</h2>{posts.length?posts.slice(0,20).map(p=><article className="hub-card" key={p._id.toString()}><div className="hub-meta"><span>{p.category}</span><span>{p.authorName} · {dateLabel(p.createdAt)}</span>{mine&&<span>{p.status==='published'?'Đã duyệt':p.status==='pending'?'Chờ duyệt':'Đã ẩn'}</span>}</div><h3><Link href={`/community/${p._id}`}>{p.title}</Link></h3><p className="hub-excerpt">{p.body.slice(0,220)}{p.body.length>220?'…':''}</p><Link href={`/community/${p._id}`}>Tham gia thảo luận ↗</Link></article>):<div className="hub-empty"><h3>Khởi đầu một cuộc trò chuyện</h3><p>{mine?'Bạn chưa có bài viết ở mục này.':'Chưa có bài viết được duyệt trong mục này. Hãy chia sẻ câu hỏi hoặc dự án đầu tiên.'}</p></div>}<nav className="hub-pagination" aria-label="Phân trang bài viết">{page>1&&<Link href={href(page-1)}>← Trang trước</Link>}<span>Trang {page}</span>{posts.length>20&&<Link href={href(page+1)}>Trang tiếp →</Link>}</nav></section><aside><div className="hub-card"><span className="hub-eyebrow">CHIA SẺ ĐỂ CÙNG TIẾN BỘ</span><h2>Viết điều bạn đang nghĩ</h2><p>Bài viết và bình luận được admin duyệt trước khi công khai.</p>{user?<AcademyForm action={communityAction} label="Gửi bài để duyệt"><input type="hidden" name="action" value="post"/><label>Chủ đề<select name="category"><option>Hỏi đáp</option><option>Chia sẻ</option><option>Dự án</option></select></label><label>Tiêu đề<input name="title" required maxLength={160}/></label><label>Nội dung<textarea name="body" required rows={8} maxLength={6000} placeholder="Mục tiêu, điều đã thử, lỗi gặp phải… Không đăng mật khẩu hoặc API key."/></label></AcademyForm>:<PublicAccount label="Đăng nhập để viết bài"/>}</div><div className="hub-card hub-dark"><h3>Thử sức bằng một cuộc thi</h3><p>Luyện cách giải quyết vấn đề và so tài với cộng đồng.</p><Link href="/contests">Khám phá contest →</Link></div></aside></div></main>;
}
