import type { BlockChallenge, BlockWorld } from "./blocks";
const world = (name: string, goal: [number, number], extras: Partial<BlockWorld> = {}): BlockWorld => ({ name, size: 6, start: { x: 0, y: 0, direction: 0 }, goal: { x: goal[0], y: goal[1] }, walls: [], stars: [], ...extras });
export const blockChallenges: BlockChallenge[] = [
  { slug: "first-swim", title: "01 · Chuyến bơi đầu tiên", description: "Ghép lệnh đầu tiên để cá heo tới chiếc phao.", level: "Cơ bản", instructions: ["Cá heo bắt đầu ở (0,0), nhìn sang phải.", "Đi tới đích (3,0). Một khối Đi tới có thể chọn số bước.", "Đạt đích: 90 điểm; dùng tối đa 1 khối: thêm 10 điểm."], allowed: ["move"], maxBlocks: 1, worlds: [world("Đường thẳng", [3,0])] },
  { slug: "turn-the-corner", title: "02 · Qua khúc cua", description: "Thứ tự đi tới và quay quyết định đường đi.", level: "Cơ bản", instructions: ["Đi tới (2,0), quay phải rồi tới (2,2).", "Không đi qua tường. Hướng phải là quay theo chiều kim đồng hồ."], allowed: ["move","left","right"], maxBlocks: 3, worlds: [world("Chữ L", [2,2], { walls: [{x:0,y:1},{x:1,y:1},{x:3,y:0}] })] },
  { slug: "star-delivery", title: "03 · Mang sao về đích", description: "Dừng đúng ô và dùng khối Nhặt sao trước khi đi tiếp.", level: "Cơ bản", instructions: ["Nhặt sao ở (1,0) và (3,0), kết thúc ở (4,0).", "Đến đích được 60 điểm, nhặt đủ sao được 30 điểm, tối đa 5 khối được 10 điểm."], allowed: ["move","collect"], maxBlocks: 5, worlds: [world("Hai ngôi sao", [4,0], { stars: [{x:1,y:0},{x:3,y:0}] })] },
  { slug: "repeat-staircase", title: "04 · Bậc thang vòng lặp", description: "Một mẫu nhỏ được lặp ba lần để đi đường bậc thang.", level: "Cơ bản", instructions: ["Ghép mẫu đi tới → quay phải → đi tới → quay trái trong khối Lặp 3 lần.", "Đến (3,3); không quá 5 khối để đạt điểm tối đa. Khối lặp cũng được tính một khối."], allowed: ["move","left","right","repeat"], maxBlocks: 5, worlds: [world("Ba bậc", [3,3], { walls: [{x:2,y:0},{x:3,y:1},{x:4,y:2},{x:0,y:2},{x:1,y:3},{x:2,y:4}] })] },
  { slug: "square-patrol", title: "05 · Tuần tra hình vuông", description: "Lặp hành trình để thu thập sao ở bốn góc.", level: "Trung cấp", instructions: ["Nhặt sao ở mỗi góc hình vuông cạnh 2 ô rồi trở lại (0,0).", "Gợi ý: lặp 4 lần chuỗi nhặt sao, đi 2 bước, quay phải."], allowed: ["move","right","left","repeat","collect"], maxBlocks: 4, worlds: [world("Bốn góc", [0,0], { stars: [{x:0,y:0},{x:2,y:0},{x:2,y:2},{x:0,y:2}] })] },
  { slug: "sense-the-wall", title: "06 · Nhìn trước khi bơi", description: "Một chương trình xử lý được cả đường trống và đường bị chặn.", level: "Trung cấp", instructions: ["Nếu phía trước trống: đi 1 bước. Nếu bị chặn: quay phải rồi đi 1 bước.", "Máy chấm chạy cùng chương trình trên cả hai bản đồ. Chọn bản đồ bên sân khấu để thử."], allowed: ["move","right","ifClear"], maxBlocks: 4, worlds: [world("Có đường", [1,0]), world("Có tường", [0,1], { walls: [{x:1,y:0}] })] },
  { slug: "ocean-sweep", title: "07 · Quét sao đại dương", description: "Lặp mẫu nhặt sao theo từng hàng, kết hợp hai cấp vòng lặp.", level: "Trung cấp", instructions: ["Nhặt sao tại 6 ô: (0,0),(1,0),(2,0),(2,1),(1,1),(0,1).", "Kết thúc ở (0,1). Lặp đi và nhặt để giảm số khối; tối đa 12 khối để đạt 100 điểm."], allowed: ["move","left","right","repeat","collect"], maxBlocks: 12, worlds: [world("Hai hàng sao", [0,1], { stars: [{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:2,y:1},{x:1,y:1},{x:0,y:1}] })] },
  { slug: "adaptive-explorer", title: "08 · Nhà thám hiểm thích nghi", description: "Lặp và kiểm tra đường đi để xử lý hai mê cung khác nhau.", level: "Nâng cao", instructions: ["Lặp 5 lần: nếu phía trước trống thì đi 1 bước, nếu không thì quay phải.", "Chương trình phải kết thúc đúng đích trên cả hai bản đồ.", "Tối đa 4 khối để đạt trọn 100 điểm."], allowed: ["move","left","right","repeat","ifClear"], maxBlocks: 4, worlds: [world("Rẽ sớm", [1,3], { walls: [{x:2,y:0}] }), world("Rẽ muộn", [3,1], { walls: [{x:4,y:0}] })] },
];
