export const eduActivities = [
  {slug:'code-together',title:'Cùng giải một bài',category:'Thực hành',symbol:'</>',intro:'Một bài toán, nhiều góc nhìn. So sánh cách tiếp cận và học từ lời giải của nhau.',steps:['Đọc đề và tự viết ra đầu vào, đầu ra.','Thử một lời giải đơn giản trước khi tối ưu.','Chia sẻ cách làm, độ phức tạp và một trường hợp biên.'],result:'Một lời giải chạy được và phần giải thích rõ ràng.',href:'/dashboard#practice',cta:'Mở kho bài tập'},
  {slug:'project-lab',title:'Phòng thử nghiệm dự án',category:'Sáng tạo',symbol:'{ }',intro:'Biến một ý tưởng nhỏ thành sản phẩm có thể dùng thử, từng tính năng một.',steps:['Chọn một nhu cầu cụ thể và giới hạn phiên bản đầu tiên.','Dựng giao diện, kết nối dữ liệu và kiểm tra luồng chính.','Ghi README, chụp màn hình và chia sẻ điều đã học.'],result:'Một bản demo nhỏ có hướng dẫn chạy và danh sách việc cần cải thiện.',href:'/community',cta:'Chia sẻ dự án'},
  {slug:'code-review',title:'Góc review code',category:'Kết nối',symbol:'✓',intro:'Nhìn lại code với một góc nhìn khác: dễ hiểu hơn, ít lỗi hơn và có lý do rõ ràng.',steps:['Chuẩn bị đoạn code nhỏ cùng mục tiêu và câu hỏi.','Nêu cách chạy lại lỗi hoặc bộ test đang dùng.','Phản hồi vào vấn đề cụ thể, thử sửa và ghi lại thay đổi.'],result:'Một bản sửa có giải thích, không chỉ một đoạn code được viết lại.',href:'/community',cta:'Mở khu trao đổi'},
  {slug:'algorithm-arena',title:'Đấu trường thuật toán',category:'Thực hành',symbol:'⌁',intro:'Thử sức trong giới hạn thời gian, sau đó dành thời gian hiểu những bài chưa giải được.',steps:['Xem cuộc thi được công bố và đọc kỹ thể lệ.','Chọn ngôn ngữ được hỗ trợ, kiểm tra cách nộp bài.','Sau cuộc thi, làm lại bài khó và tổng kết chiến thuật.'],result:'Kinh nghiệm phân bổ thời gian và danh sách chủ đề cần ôn.',href:'/contests',cta:'Xem các cuộc thi'},
  {slug:'web-design',title:'Thử thách giao diện',category:'Sáng tạo',symbol:'↗',intro:'Rèn mắt thiết kế cùng kỹ năng lập trình qua những giao diện nhỏ nhưng chỉn chu.',steps:['Chọn một màn hình và xác định nội dung quan trọng.','Dựng bố cục cho desktop và mobile.','Kiểm tra bàn phím, độ tương phản và trạng thái trống.'],result:'Một giao diện responsive với các trạng thái tương tác rõ ràng.',href:'/programs/frontend',cta:'Khám phá hướng Frontend'},
  {slug:'python-workshop',title:'Python mỗi ngày',category:'Thực hành',symbol:'Py',intro:'Tìm một thao tác lặp lại và thử dùng Python để làm nó đơn giản hơn.',steps:['Mô tả thao tác thủ công và dữ liệu đầu vào.','Viết script nhỏ, giữ nguyên bản dữ liệu gốc.','Thử dữ liệu thiếu hoặc sai định dạng và thêm thông báo lỗi.'],result:'Một công cụ nhỏ, có thể chạy lại và giải thích cách sử dụng.',href:'/programs/python',cta:'Khám phá Python'},
  {slug:'data-stories',title:'Kể chuyện bằng dữ liệu',category:'Sáng tạo',symbol:'DB',intro:'Bắt đầu từ một câu hỏi rõ ràng, tìm dữ liệu phù hợp và trình bày kết quả có căn cứ.',steps:['Xác định câu hỏi và ý nghĩa của từng cột dữ liệu.','Kiểm tra dữ liệu thiếu, trùng và điều kiện JOIN.','Trình bày kết quả cùng giới hạn của phân tích.'],result:'Một truy vấn có thể kiểm tra và phần kết luận không vượt quá dữ liệu.',href:'/programs/sql',cta:'Khám phá SQL'},
  {slug:'learning-circle',title:'Nhóm học cùng nhau',category:'Kết nối',symbol:'◎',intro:'Chia sẻ một mục tiêu vừa sức, một điều đã hiểu và một điều đang vướng.',steps:['Chọn chủ đề đang học và viết mục tiêu cụ thể.','Chia sẻ tiến độ bằng ví dụ thay vì chỉ số giờ học.','Đặt câu hỏi rõ ràng và giúp người khác tái hiện vấn đề.'],result:'Một ghi chú học tập và bước tiếp theo có thể bắt tay vào làm.',href:'/community',cta:'Tham gia cộng đồng'},
  {slug:'demo-story',title:'Kể câu chuyện sản phẩm',category:'Kết nối',symbol:'→',intro:'Luyện cách trình bày dự án để người khác hiểu vấn đề, giải pháp và lựa chọn của bạn.',steps:['Giới thiệu người dùng và vấn đề cần giải quyết.','Demo một luồng chính và giải thích quyết định kỹ thuật.','Nêu giới hạn hiện tại, xin phản hồi và chọn bước cải thiện.'],result:'Một bài giới thiệu dự án ngắn gọn, có demo và hướng phát triển.',href:'/community',cta:'Chia sẻ câu chuyện của bạn'},
];
