export type EmailDraft = { to: string; recipient: string; subject: string; heading: string; body: string; ctaLabel: string; ctaUrl: string; theme: 'welcome' | 'course' | 'mentoring' };
export const emailPresets: Record<EmailDraft['theme'], Omit<EmailDraft,'to'|'recipient'|'theme'>> = {
 welcome:{subject:'Chào mừng bạn đến với DolphinX Education',heading:'Hành trình mới.\nKhả năng mới.',body:'Chào bạn,\n\nRất vui được đồng hành cùng bạn trên hành trình học lập trình. Bắt đầu từ những kiến thức nhỏ, thực hành mỗi ngày và từng bước tạo nên sản phẩm của riêng mình.\n\nHãy khám phá khóa học và chọn bước đầu tiên phù hợp với bạn.',ctaLabel:'Khám phá khóa học',ctaUrl:''},
 course:{subject:'Khám phá khóa học cùng DolphinX',heading:'Từ dòng code đầu tiên\nđến sản phẩm của bạn.',body:'Chào bạn,\n\nDolphinX gửi bạn thông tin khóa học phù hợp với mục tiêu của mình. Chương trình kết hợp kiến thức nền tảng, thực hành và dự án.\n\nXem nội dung chi tiết qua liên kết bên dưới. Nếu cần tư vấn, bạn có thể trả lời trực tiếp email này.',ctaLabel:'Xem nội dung khóa học',ctaUrl:''},
 mentoring:{subject:'Cùng xây dựng lộ trình học của bạn',heading:'Một mục tiêu rõ ràng.\nMột người đồng hành.',body:'Chào bạn,\n\nCùng mentor DolphinX tìm hiểu mục tiêu, trình độ hiện tại và xây dựng lộ trình phù hợp.\n\nHọc online 1–1, mỗi buổi 2 giờ. Bạn có thể trao đổi về buổi học thử trước khi lựa chọn chương trình.',ctaLabel:'Trao đổi cùng mentor',ctaUrl:''}
};
const escapeHtml = (s:string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function validateEmailDraft(input: unknown): EmailDraft {
 if(!input || typeof input!=='object') throw new Error('Nội dung email không hợp lệ.');
 const d=input as Record<string,unknown>;
 for(const [key,max] of Object.entries({to:254,recipient:100,subject:180,heading:180,body:10000,ctaLabel:60,ctaUrl:1500})) if(typeof d[key]!=='string'||(d[key] as string).length>max) throw new Error(`Kiểm tra trường ${key}.`);
 if(!/^[^\s<>@,;]+@[^\s<>@,;]+\.[^\s<>@,;]+$/.test(d.to as string)) throw new Error('Nhập một địa chỉ email người nhận hợp lệ.');
 if(/[\r\n]/.test(d.subject as string)||![d.subject,d.heading,d.body].every(s=>(s as string).trim())) throw new Error('Tiêu đề và nội dung không được để trống.');
 if(!['welcome','course','mentoring'].includes(String(d.theme))) throw new Error('Mẫu thư không hợp lệ.');
 if(d.ctaUrl){let url;try{url=new URL(d.ctaUrl as string);}catch{throw new Error('Liên kết nút không hợp lệ.');}if(url.protocol!=='https:'||url.username||url.password) throw new Error('Liên kết trong email phải dùng HTTPS.');if(!(d.ctaLabel as string).trim()) throw new Error('Nhập tên cho nút liên kết.');}
 return d as EmailDraft;
}
export function renderEmail(d: EmailDraft, imageUrl='/brand/course-coding-mascot-v4.png') {
 const e=escapeHtml;
 const accent=d.theme==='mentoring'?'#12a7a9':d.theme==='course'?'#8360cf':'#168ec9';
 const html=`<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;background:#edf2f8;font-family:Arial,Helvetica,sans-serif;color:#18344f"><div style="display:none;max-height:0;overflow:hidden">${e(d.subject)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:white;border-radius:18px;overflow:hidden"><tr><td style="padding:27px 32px;border-bottom:1px solid #eaf0f6"><strong style="font-size:25px;letter-spacing:-1px">Dolphin<span style="color:${accent}">X</span></strong><span style="display:block;font-size:9px;letter-spacing:4px;color:#7891a8;margin-top:5px">EDUCATION</span></td></tr><tr><td style="background:#102f4d;padding:34px 32px"><p style="font-size:10px;letter-spacing:2px;color:#79d5e2;margin:0 0 18px">LEARN. BUILD. GROW.</p><h1 style="font-size:32px;line-height:1.25;font-weight:700;letter-spacing:-1px;margin:0;color:white">${e(d.heading).replace(/\n/g,'<br>')}</h1><p style="font-size:12px;color:#a1bdd3;margin:18px 0 0">Một bước nhỏ hôm nay. Một tương lai rộng mở.</p></td></tr><tr><td><img src="${e(imageUrl)}" width="600" alt="Cá heo DolphinX cùng bạn học lập trình" style="display:block;width:100%;height:auto;border:0"></td></tr><tr><td style="padding:30px 32px"><p style="font-size:11px;color:${accent};letter-spacing:1px;font-weight:bold">DÀNH CHO ${e(d.recipient.trim()||'BẠN')}</p><div style="font-size:15px;line-height:1.9;color:#536d84">${e(d.body).replace(/\n/g,'<br>')}</div>${d.ctaUrl&&/^https:\/\//i.test(d.ctaUrl)?`<table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:26px"><tr><td bgcolor="${accent}" style="border-radius:8px"><a href="${e(d.ctaUrl)}" style="display:inline-block;padding:15px 24px;font-size:13px;font-weight:bold;color:white;text-decoration:none">${e(d.ctaLabel)} →</a></td></tr></table>`:''}<p style="margin:30px 0 0;font-size:13px;line-height:1.8;color:#7890a6">Hẹn gặp bạn trên hành trình học tập,<br><strong style="color:#294965">Đội ngũ DolphinX Education</strong></p></td></tr><tr><td style="padding:22px 32px;background:#f6f9fc;border-top:1px solid #e7eff5"><p style="font-size:11px;color:#7b91a5;line-height:1.8;margin:0">Học lập trình · Phát triển tư duy · Tạo sản phẩm<br>Bạn có thể trả lời email để trao đổi hoặc yêu cầu ngừng nhận thư.</p></td></tr></table><p style="font-size:10px;color:#92a3b5;letter-spacing:1px">DOLPHINX EDUCATION · CODE YOUR NEXT CHAPTER</p></td></tr></table></body></html>`;
 return {html,text:`${d.heading}\n\n${d.body}\n\n${d.ctaUrl?`${d.ctaLabel}: ${d.ctaUrl}\n\n`:''}Đội ngũ DolphinX Education\nBạn có thể trả lời email để trao đổi hoặc yêu cầu ngừng nhận thư.`};
}
