import type { PracticeResource } from "./resources";
const mdn = "https://developer.mozilla.org/en-US/docs/Learn_web_development";
const typescript = "https://www.typescriptlang.org/docs/handbook/";
const git = "https://git-scm.com/book/en/v2";
export const extraResources: PracticeResource[] = [
  { id: "accessible-form", title: "Form đăng ký dùng được bằng bàn phím", topic: "Frontend", kind: "Mini project", level: "Cơ bản", minutes: 50, description: "Xây form có label, thông báo lỗi và trạng thái gửi rõ ràng.", setup: "Tạo form tên, email, mật khẩu và nút Đăng ký. Không gửi thông tin thật; mô phỏng phản hồi sau 500ms.", tasks: ["Liên kết label với input, dùng type và autocomplete phù hợp.", "Liên kết lỗi với trường qua aria-describedby.", "Trong khi gửi, ngăn gửi lặp; sau lỗi mạng cho phép thử lại."], checks: ["Tab đi qua toàn bộ form; focus nhìn thấy.", "Email rỗng không gửi; lỗi không chỉ dựa vào màu.", "Nhấn gửi hai lần chỉ tạo một tác vụ."], hint: "Dùng form onSubmit, cờ pending và role=alert cho lỗi chung.", source: mdn },
  { id: "css-dashboard", title: "Dashboard co giãn không tràn ngang", topic: "Frontend", kind: "Mini project", level: "Trung cấp", minutes: 80, description: "Luyện Grid, sidebar và bố trí bảng trên màn hình nhỏ.", setup: "Sidebar, header, ba thẻ thống kê và bảng 6 cột với 10 dòng dữ liệu giả.", tasks: ["Desktop: sidebar 240px, nội dung minmax(0,1fr).", "Mobile: menu mở/đóng có aria-expanded.", "Chỉ vùng bảng được cuộn ngang."], checks: ["Không tràn trang tại 390,768,1280px.", "Tên dài 100 ký tự không phá bố cục.", "Escape đóng menu, focus trở lại nút mở."], hint: "min-width:0 giúp Grid/Flex co lại; overflow-x:auto đặt ở wrapper bảng.", source: mdn },
  { id: "js-search-race", title: "Tìm kiếm không trả kết quả cũ", topic: "JavaScript", kind: "Debug", level: "Trung cấp", minutes: 45, description: "Xử lý cuộc đua request khi người dùng gõ nhanh.", setup: "fakeSearch('r') trả sau 800ms; fakeSearch('react') trả sau 100ms. Kết quả gồm query tương ứng.", tasks: ["Tái hiện r ghi đè react.", "Chỉ request mới nhất được cập nhật UI bằng request ID.", "Xử lý query rỗng, loading và lỗi."], checks: ["Gõ r rồi react: kết quả cuối là react.", "Xóa input khi đang tải giữ kết quả rỗng.", "Lỗi request cũ không thay trạng thái request mới."], hint: "Cả success, catch và finally phải kiểm tra ID mới nhất.", source: mdn },
  { id: "js-pagination", title: "Phân trang không bỏ sót phần tử", topic: "JavaScript", kind: "Thuật toán", level: "Cơ bản", minutes: 30, description: "Viết hàm phân trang thuần và kiểm tra ranh giới.", setup: "paginate(items,page,size) trả {items,totalPages}. page/size là số nguyên dương; trang vượt cuối trả items rỗng.", tasks: ["Kiểm tra page/size trước khi slice.", "Không sửa mảng đầu vào.", "Viết test cho 0,1,10,11 phần tử với size=10."], checks: ["[1,2,3,4,5],page=2,size=2 trả [3,4] và totalPages=3.", "Page=4 với mẫu trên trả [].", "Size=0, page=-1, số thập phân bị từ chối; dữ liệu rỗng có 0 trang."], hint: "Bắt đầu tại (page-1)*size; số trang dùng Math.ceil.", source: mdn },
  { id: "react-shopping-list", title: "Danh sách mua sắm có bộ lọc", topic: "React", kind: "Mini project", level: "Cơ bản", minutes: 70, description: "Controlled input, cập nhật bất biến và key ổn định.", setup: "Mỗi mục có id,title,bought. Lưu trong state của trang, chưa cần backend.", tasks: ["Thêm, đánh dấu đã mua và xóa theo id.", "Lọc tất cả/chưa mua/đã mua, đếm mục còn lại.", "Từ chối tên chỉ có khoảng trắng; các mục trùng tên vẫn độc lập."], checks: ["Đánh dấu một mục không đổi mục khác.", "Xóa khi đang lọc vẫn xóa đúng id.", "Số lượng còn lại khớp dữ liệu gốc."], hint: "Không dùng index làm key; dùng map/filter và suy ra số lượng khi render.", source: "https://react.dev/learn" },
  { id: "react-persistent-notes", title: "Ghi chú lưu trên trình duyệt", topic: "React", kind: "Mini project", level: "Trung cấp", minutes: 90, description: "Tách lưu trữ khỏi UI và xử lý JSON bị hỏng.", setup: "Ghi chú có title/body/updatedAt. Dùng key localStorage riêng; không lưu thông tin nhạy cảm.", tasks: ["Đọc khi client sẵn sàng, không ghi mảng rỗng trước khi tải xong.", "Thêm, sửa, xóa và lưu ghi chú.", "Kiểm tra schema, báo khi storage không khả dụng."], checks: ["Reload giữ ghi chú vừa sửa.", "Giá trị '{bad' không làm crash.", "JSON hợp lệ nhưng sai kiểu bị từ chối."], hint: "Dùng cờ hydrated phân biệt chưa đọc storage và dữ liệu rỗng.", source: "https://react.dev/learn" },
  { id: "ts-api-union", title: "Trạng thái tải bằng TypeScript", topic: "TypeScript", kind: "Mini project", level: "Trung cấp", minutes: 40, description: "Dùng discriminated union để thành công luôn có dữ liệu.", setup: "LoadState<T>: idle, loading, success có data, error có message. renderLabel nhận LoadState<string[]>.", tasks: ["Dùng status và switch từng trường hợp.", "Dùng never kiểm tra exhaustiveness.", "Thêm cancelled rồi xử lý lỗi compiler ở nhánh thiếu."], checks: ["{status:'success'} không biên dịch vì thiếu data.", "Chỉ đọc data sau khi thu hẹp status.", "Không dùng any để bỏ qua lỗi."], hint: "Mỗi trạng thái là một object type riêng; assertNever nhận never.", source: typescript },
  { id: "ts-unknown-input", title: "Kiểm tra unknown từ API", topic: "TypeScript", kind: "Debug", level: "Trung cấp", minutes: 50, description: "Phân biệt type tĩnh với dữ liệu thực nhận.", setup: "parseCourse(value:unknown) trả {id:string,title:string,lessons:number}; lessons nguyên không âm, id/title không rỗng.", tasks: ["Từ chối null, array và primitive.", "Kiểm tra từng thuộc tính trước khi tạo kết quả.", "Bỏ thuộc tính thừa, báo rõ trường sai."], checks: ["{id:'a',title:'JS',lessons:5} hợp lệ.", "lessons:'5',NaN,-1,1.5 bị từ chối.", "Trường admin:true không được giữ lại."], hint: "typeof null là object; cần kiểm tra null và Array.isArray riêng.", source: typescript },
  { id: "git-feature-branch", title: "Một tính năng, ba commit", topic: "Git", kind: "Workshop", level: "Cơ bản", minutes: 45, description: "Luyện quy trình nhánh trong repository thử nghiệm.", setup: "Tạo thư mục mới, git init và README. Không dùng repo công việc thật hay đẩy bí mật lên remote.", tasks: ["Tạo nhánh feature/course-card.", "Ba commit: HTML, CSS, hướng dẫn chạy.", "Xem diff trước commit rồi merge về nhánh chính."], checks: ["git log --oneline có mô tả rõ.", "git status sạch sau merge.", "README đủ để người khác chạy dự án."], hint: "git diff và git diff --staged xem hai nhóm thay đổi khác nhau.", source: git },
  { id: "git-merge-conflict", title: "Giải conflict không mất nội dung", topic: "Git", kind: "Debug", level: "Trung cấp", minutes: 40, description: "Hiểu xung đột bằng ví dụ nhỏ kiểm chứng được.", setup: "Trong repo thử nghiệm, hai nhánh sửa cùng một dòng tiêu đề README theo hai cách.", tasks: ["Merge để tạo conflict, đọc các marker.", "Kết hợp ý nghĩa hai nhánh, không chọn bừa một phía.", "Kiểm tra, stage và commit kết quả."], checks: ["README không còn <<<<<<<.", "git status không còn unmerged paths.", "Giải thích vì sao Git không tự chọn được dòng tiêu đề."], hint: "Conflict cần quyết định về nội dung; xem diff trước khi đánh dấu đã xử lý.", source: git },
  { id: "python-log-summary", title: "Tổng hợp log và đếm lỗi", topic: "Python", kind: "Mini project", level: "Trung cấp", minutes: 60, description: "Đọc từng dòng và tạo báo cáo đối chiếu được.", setup: "INFO|started\nERROR|timeout\nWARN|slow\nERROR|offline\nbad-row\nQuy ước: LEVEL thuộc INFO/WARN/ERROR, message không rỗng.", tasks: ["parse_line trả bản ghi hoặc lỗi có số dòng.", "Đếm từng mức độ và số dòng lỗi.", "Xuất JSON, không nạp cả file vào RAM."], checks: ["Mẫu: INFO=1,WARN=1,ERROR=2,invalid=1.", "File rỗng: mọi bộ đếm bằng 0.", "ERROR| không hợp lệ; message chứa | vẫn giữ nguyên."], hint: "split('|',1) chỉ tách lần đầu; enumerate bắt đầu từ 1.", source: "https://docs.python.org/3/tutorial/" },
  { id: "sql-active-days", title: "Đếm ngày học không đếm trùng", topic: "SQL", kind: "Truy vấn", level: "Trung cấp", minutes: 50, description: "Phân biệt ngày riêng biệt và số lần ghi nhận hoạt động.", setup: "CREATE TABLE activity(user_id int, day date); INSERT INTO activity VALUES (1,'2026-09-01'),(1,'2026-09-01'),(1,'2026-09-02'),(2,'2026-09-02');", tasks: ["Đếm ngày riêng biệt theo user_id.", "Chỉ trả người có ít nhất 2 ngày.", "Thêm bộ lọc khoảng ngày trước khi group."], checks: ["User 1 có 2 ngày, không phải 3.", "Ít nhất 2 ngày chỉ trả user 1.", "Khoảng không có dữ liệu trả rỗng."], hint: "COUNT(DISTINCT day); điều kiện kết quả tổng hợp nằm trong HAVING.", source: "https://www.postgresql.org/docs/current/tutorial.html" },
];
