export type PracticeResource = { id: string; title: string; topic: string; kind: string; level: string; minutes: number; description: string; setup: string; tasks: string[]; checks: string[]; hint: string; source: string };
import { extraResources } from "./extra-resources";
export const resourceSources = [
  { title: "MDN · Nền tảng web", topic: "Frontend", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development", description: "HTML, CSS, JavaScript và các bài kiểm tra kỹ năng. Tài liệu tiếng Anh." },
  { title: "React · Học qua ví dụ", topic: "React", url: "https://react.dev/learn", description: "Component, props, state và cách chia sẻ dữ liệu. Tài liệu tiếng Anh." },
  { title: "Python · Tutorial chính thức", topic: "Python", url: "https://docs.python.org/3/tutorial/", description: "Kiểu dữ liệu, điều khiển luồng, hàm, module và xử lý lỗi. Tài liệu tiếng Anh." },
  { title: "PostgreSQL · SQL căn bản", topic: "SQL", url: "https://www.postgresql.org/docs/current/tutorial.html", description: "Bảng, truy vấn, phép nối và hàm tổng hợp. Tài liệu tiếng Anh." },
  { title: "Scratch · Ý tưởng sáng tạo", topic: "Kéo thả", url: "https://scratch.mit.edu/ideas", description: "Ý tưởng dự án từ Scratch. Phòng khối lệnh DolphinX là công cụ riêng, không phải Scratch chính thức." },
  { title: "TypeScript · Handbook", topic: "TypeScript", url: "https://www.typescriptlang.org/docs/handbook/", description: "Kiểu dữ liệu, narrowing và hợp đồng dữ liệu. Tài liệu tiếng Anh." },
  { title: "Git · Pro Git", topic: "Git", url: "https://git-scm.com/book/en/v2", description: "Version control, nhánh và cộng tác. Sách chính thức, truy cập miễn phí." },
];
export const practiceResources: PracticeResource[] = [
  ...extraResources,
  { id: "responsive-cards", title: "Thư viện khóa học responsive", topic: "Frontend", kind: "Mini project", level: "Cơ bản", minutes: 60, description: "Biến dữ liệu khóa học thành giao diện dùng được trên điện thoại và desktop.", setup: 'Tạo index.html và style.css. Dữ liệu: Python (Cơ bản), React (Trung cấp), SQL (Cơ bản). Mỗi khóa có tên, mô tả và nút xem chi tiết.', tasks: ["Dùng heading theo thứ bậc, main và article để cấu trúc trang.", "Hiển thị 1 cột ở 390px, 2 cột ở 768px và 3 cột ở 1280px.", "Thêm trạng thái hover và focus; mọi nút phải có tên rõ ràng."], checks: ["Không tràn ngang ở cả 3 kích thước.", "Tab lần lượt đến được cả 3 link khóa học.", "Mỗi trang chỉ có một h1; ảnh có alt phù hợp."], hint: "Bắt đầu mobile-first, dùng CSS Grid với minmax; đừng đặt chiều rộng cố định cho thẻ.", source: resourceSources[0].url },
  { id: "debug-cart", title: "Debug tổng tiền giỏ hàng", topic: "JavaScript", kind: "Debug", level: "Cơ bản", minutes: 25, description: "Tìm lỗi nối chuỗi và kiểm tra dữ liệu đầu vào trước khi tính tổng.", setup: 'const items = [{ price: "120", qty: 2 }, { price: "30", qty: 1 }];\nconst total = items.reduce((sum, item) => sum + item.price, 0);\n// Kết quả cần là 270, không phải chuỗi.', tasks: ["Giải thích hai lỗi trong cách tính hiện tại.", "Viết hàm cartTotal(items) trả về tổng price × qty dạng number.", "Ném Error nếu price âm, không hữu hạn hoặc qty không phải số nguyên dương."], checks: ["cartTotal([]) trả 0.", "Dữ liệu mẫu trả 270.", "price='abc', price=-1 và qty=1.5 đều bị từ chối."], hint: "Chuyển price bằng Number rồi dùng Number.isFinite; khởi tạo reduce bằng số 0.", source: resourceSources[0].url },
  { id: "react-filter", title: "Bộ lọc danh sách học tập", topic: "React", kind: "Mini project", level: "Trung cấp", minutes: 75, description: "Kết hợp tìm kiếm, lọc và trạng thái rỗng mà không lưu state dư thừa.", setup: 'courses = [{id:1,title:"Python",level:"Cơ bản"},{id:2,title:"React",level:"Trung cấp"},{id:3,title:"SQL",level:"Cơ bản"}]', tasks: ["Xây input tìm kiếm và select trình độ có label.", "Kết hợp hai điều kiện lọc; không phân biệt hoa thường.", "Hiển thị số kết quả, trạng thái rỗng và nút xóa bộ lọc."], checks: ["Từ khóa 'RE' tìm được React.", "Chọn Cơ bản và gõ React cho 0 kết quả.", "Xóa bộ lọc trả lại 3 khóa; không sửa mảng gốc."], hint: "Chỉ lưu query và level trong state. Danh sách kết quả được suy ra bằng filter trong render.", source: resourceSources[1].url },
  { id: "python-expenses", title: "Sổ chi tiêu bằng Python", topic: "Python", kind: "Mini project", level: "Cơ bản", minutes: 60, description: "Đọc dữ liệu và tổng hợp chi phí theo danh mục bằng dictionary.", setup: 'expenses = [{"category":"food","amount":30000},{"category":"travel","amount":15000},{"category":"food","amount":20000}]', tasks: ["Viết summarize(expenses) trả dictionary tổng tiền từng danh mục.", "Viết riêng hàm kiểm tra amount là số không âm, category không rỗng.", "Thêm giao diện CLI hiển thị kết quả theo tên danh mục tăng dần."], checks: ["Mẫu trả food=50000, travel=15000.", "Danh sách rỗng trả dictionary rỗng.", "Amount âm hoặc category rỗng báo lỗi rõ ràng."], hint: "Dùng totals.get(category, 0); tách input/print khỏi hàm nghiệp vụ để kiểm thử dễ hơn.", source: resourceSources[2].url },
  { id: "python-mutable-default", title: "Chiếc list nhớ quá lâu", topic: "Python", kind: "Debug", level: "Trung cấp", minutes: 20, description: "Khám phá vì sao hai lần gọi hàm lại dùng chung dữ liệu.", setup: 'def add_task(title, tasks=[]):\n    tasks.append(title)\n    return tasks\n\nprint(add_task("A"))\nprint(add_task("B"))', tasks: ["Dự đoán đầu ra của hai lệnh print trước khi chạy.", "Giải thích thời điểm giá trị mặc định được tạo.", "Sửa hàm để mỗi lần không truyền tasks tạo list mới; truyền list thì vẫn thêm vào list đó."], checks: ["Lần gọi thứ hai chỉ trả ['B'] khi không truyền list.", "Truyền list có ['A'] rồi thêm B trả ['A','B'].", "Không dùng biến toàn cục."], hint: "Dùng None làm giá trị mặc định, tạo list trong thân hàm khi tasks is None.", source: resourceSources[2].url },
  { id: "sql-sales", title: "Báo cáo doanh thu có đơn hủy", topic: "SQL", kind: "Truy vấn", level: "Cơ bản", minutes: 35, description: "Lọc trạng thái và tổng hợp doanh thu chính xác theo khách hàng.", setup: "CREATE TABLE orders (id int, customer text, amount int, status text);\nINSERT INTO orders VALUES (1,'An',100,'paid'),(2,'An',50,'cancelled'),(3,'Binh',200,'paid'),(4,'An',80,'paid');", tasks: ["Tạo dữ liệu trong PostgreSQL local hoặc môi trường học riêng.", "Viết truy vấn tổng amount và số đơn paid theo customer.", "Sắp xếp doanh thu giảm dần, tên tăng dần khi bằng nhau."], checks: ["Binh: doanh thu 200, 1 đơn.", "An: doanh thu 180, 2 đơn.", "Đơn cancelled không được tính; bảng rỗng không tạo khách giả."], hint: "WHERE lọc các hàng trước GROUP BY. Dùng COUNT(*) cho số đơn, SUM(amount) cho doanh thu.", source: resourceSources[3].url },
  { id: "sql-missing", title: "Tìm học viên chưa đăng ký", topic: "SQL", kind: "Truy vấn", level: "Trung cấp", minutes: 40, description: "Dùng JOIN để tìm dữ liệu thiếu mà không bị nhân bản kết quả.", setup: "CREATE TABLE learners(id int, name text);\nCREATE TABLE enrollments(user_id int, course_id int);\nINSERT INTO learners VALUES (1,'An'),(2,'Binh'),(3,'Chi');\nINSERT INTO enrollments VALUES (1,10),(1,11),(3,10);", tasks: ["Viết truy vấn trả học viên không có enrollment nào.", "Giải lại bằng NOT EXISTS và so sánh cách hiểu hai cách.", "Thêm một enrollment cho Binh rồi chạy lại."], checks: ["Ban đầu chỉ trả Binh (id=2).", "Sau khi Binh có enrollment, kết quả rỗng.", "Một người có nhiều enrollment không làm sai danh sách chưa đăng ký."], hint: "LEFT JOIN giữ phía learners; kiểm tra khóa phía enrollment là NULL. NOT EXISTS kiểm tra từng học viên.", source: resourceSources[3].url },
  { id: "js-frequency", title: "Bộ đếm từ không phân biệt hoa thường", topic: "JavaScript", kind: "Thuật toán", level: "Trung cấp", minutes: 35, description: "Chuẩn hóa chuỗi, đếm bằng Map và xử lý trường hợp biên.", setup: 'Viết wordCounts(text). Quy ước: từ chỉ gồm chữ ASCII a–z; ký tự khác là dấu phân cách. Trả mảng [từ, số lần], sắp xếp theo từ. Ví dụ "Hi, hi! Code." → [["code",1],["hi",2]].', tasks: ["Tách các từ theo quy ước và chuyển về chữ thường.", "Đếm tần suất bằng Map hoặc object không có prototype.", "Giải thích độ phức tạp theo độ dài văn bản và số từ khác nhau."], checks: ["Chuỗi rỗng hoặc '123 !!!' trả [].", "'A a b' trả [['a',2],['b',1]].", "'constructor constructor' được đếm đúng 2 lần."], hint: "match(/[a-z]+/g) có thể trả null. Dùng Map để tránh xung đột với các thuộc tính có sẵn.", source: resourceSources[0].url },
];
