export type RoadmapStatus = "new" | "learning" | "done";
export type RoadmapNode = { id: string; title: string; description: string; practice: string };
export type RoadmapStage = { title: string; nodes: RoadmapNode[] };
export type LearningRoadmap = { slug: string; title: string; category: string; description: string; symbol: string; course: string; outcome: string; stages: RoadmapStage[] };
function stage(title: string, topics: [string, string, string][]): RoadmapStage {
  return { title, nodes: topics.map(([name, description, practice], i) => ({ id: title.toLowerCase().replace(/[^a-z0-9]/g, "-") + "-" + i, title: name, description, practice })) };
}
const foundationRoadmaps: LearningRoadmap[] = [
  { slug: "frontend", title: "Frontend Developer", category: "Theo vai trò", symbol: "</>", course: "frontend", description: "Từ trang HTML đầu tiên đến ứng dụng web tương tác.", outcome: "Xây dựng website responsive và ứng dụng React có dữ liệu.",
    stages: [
      stage("Web foundations", [["Internet & HTTP", "Hiểu cách trình duyệt gửi yêu cầu và máy chủ trả nội dung.", "Mở Network trong DevTools, tìm request HTML và giải thích status code."], ["HTML ngữ nghĩa", "Dùng heading, landmark, link và form đúng mục đích.", "Tạo trang giới thiệu có header, main, footer và form liên hệ."]]),
      stage("Visual interface", [["CSS & layout", "Sắp xếp giao diện bằng box model, Flexbox và Grid.", "Dựng bố cục danh sách khóa học bằng CSS Grid."], ["Responsive & accessibility", "Thiết kế cho nhiều kích thước và thao tác bằng bàn phím.", "Kiểm tra trang ở 320px, 768px và điều hướng toàn bộ bằng Tab."]]),
      stage("JavaScript", [["Biến, hàm & dữ liệu", "Làm việc với array, object, scope và các phép biến đổi dữ liệu.", "Lọc và sắp xếp danh sách khóa học theo tên."], ["DOM & async", "Xử lý sự kiện, Promise, fetch và trạng thái lỗi.", "Tạo ô tìm kiếm có trạng thái đang tải, rỗng và lỗi."]]),
      stage("React", [["Component & state", "Chia giao diện thành component và quản lý trạng thái tương tác.", "Làm bộ lọc khóa học với input có kiểm soát."], ["Routing & data", "Tách trang, tải dữ liệu và phân biệt công việc phía server/client.", "Xây trang danh sách và trang chi tiết dùng cùng nguồn dữ liệu."]]),
      stage("Ship a project", [["Git & kiểm thử", "Theo dõi thay đổi và kiểm tra các hành vi quan trọng.", "Tạo nhánh tính năng và viết kiểm thử cho bộ lọc."], ["Dự án portfolio", "Kết hợp giao diện, dữ liệu, responsive và triển khai.", "Hoàn thiện website khóa học; ghi README và cách chạy dự án."]]),
    ] },
  { slug: "backend", title: "Backend Developer", category: "Theo vai trò", symbol: "{ }", course: "sql", description: "Hiểu API, dữ liệu và quyền truy cập phía máy chủ.", outcome: "Xây API có kiểm tra dữ liệu, tài khoản và phân quyền.",
    stages: [
      stage("Server foundations", [["HTTP & API", "Hiểu method, status code, header và vòng đời request.", "Thiết kế GET danh sách và POST tạo khóa học."], ["JavaScript phía server", "Tổ chức module và xử lý tác vụ bất đồng bộ.", "Viết hàm đọc dữ liệu có xử lý lỗi và timeout."]]),
      stage("Data design", [["Mô hình dữ liệu", "Xác định thực thể, quan hệ và ràng buộc trước khi viết truy vấn.", "Mô tả học viên, khóa học và đăng ký học."], ["SQL & truy vấn", "Đọc và cập nhật dữ liệu có điều kiện, tránh ghép chuỗi đầu vào.", "Viết truy vấn lấy khóa học của một học viên."]]),
      stage("Authentication", [["Mật khẩu & phiên", "Phân biệt xác thực với phân quyền; không lưu mật khẩu thuần.", "Mô tả vòng đời đăng nhập, hết hạn và đăng xuất."], ["Quyền truy cập", "Kiểm tra danh tính và quyền sở hữu ở server cho từng thao tác.", "Kiểm thử tài khoản A không đọc hoặc sửa tiến độ của B."]]),
      stage("Reliability", [["Validation & lỗi", "Kiểm tra kiểu dữ liệu, giới hạn đầu vào và phản hồi nhất quán.", "Thử API với dữ liệu thiếu, sai kiểu và quá dài."], ["Logging & giới hạn", "Theo dõi lỗi mà không ghi bí mật; hạn chế lạm dụng request.", "Thiết kế giới hạn thử đăng nhập và nhật ký không chứa mật khẩu."]]),
      stage("Production", [["Kiểm thử tích hợp", "Kiểm tra cả đường thành công lẫn từ chối quyền.", "Viết bộ test tạo, đọc, sửa và đăng xuất."], ["Triển khai API", "Quản lý biến môi trường, HTTPS và sao lưu dữ liệu.", "Triển khai API thử nghiệm và tài liệu endpoint."]]),
    ] },
  { slug: "python", title: "Python từ số 0", category: "Theo kỹ năng", symbol: "Py", course: "python", description: "Nắm cú pháp, luyện tư duy và tự động hóa công việc nhỏ.", outcome: "Viết chương trình Python xử lý dữ liệu và có kiểm thử.",
    stages: [
      stage("Getting started", [["Môi trường Python", "Hiểu trình thông dịch, virtual environment và cách chạy script.", "Tạo môi trường riêng và chạy chương trình chào hỏi."], ["Biến & kiểu dữ liệu", "Làm quen số, chuỗi, boolean và chuyển đổi kiểu.", "Viết bộ chuyển đổi nhiệt độ có kiểm tra đầu vào."]]),
      stage("Control flow", [["Điều kiện & vòng lặp", "Điều khiển luồng xử lý bằng if, for và while.", "Viết trò đoán số có giới hạn số lần thử."], ["Hàm & module", "Tách chương trình thành các hàm nhỏ với đầu vào rõ ràng.", "Tách bộ chuyển đổi đơn vị thành một module."]]),
      stage("Collections", [["List & dictionary", "Chọn cấu trúc dữ liệu phù hợp cho danh sách và tra cứu.", "Thống kê số lần xuất hiện của từng từ."], ["File & JSON", "Đọc, ghi tệp và xử lý dữ liệu có cấu trúc.", "Lưu danh sách công việc vào tệp JSON."]]),
      stage("Better programs", [["Exception & debugging", "Xử lý lỗi dự kiến và tìm nguyên nhân bằng thông tin thực tế.", "Xử lý tệp không tồn tại và JSON sai định dạng."], ["Kiểm thử hàm", "Dùng ví dụ và trường hợp biên để kiểm chứng kết quả.", "Kiểm thử hàm thống kê với dữ liệu rỗng và ký tự đặc biệt."]]),
      stage("Build something", [["Làm việc với API", "Gửi request, đọc response và xử lý lỗi kết nối.", "Đọc một API công khai và xuất kết quả thành bảng."], ["Dự án tự động hóa", "Kết hợp file, hàm và xử lý dữ liệu cho nhu cầu cụ thể.", "Tạo công cụ tổng hợp dữ liệu từ nhiều tệp CSV."]]),
    ] },
  { slug: "sql", title: "SQL & dữ liệu", category: "Theo kỹ năng", symbol: "DB", course: "sql", description: "Từ SELECT đầu tiên đến truy vấn nhiều bảng và tối ưu.", outcome: "Thiết kế dữ liệu quan hệ và viết truy vấn có thể kiểm chứng.",
    stages: [
      stage("Relational basics", [["Bảng & khóa", "Hiểu hàng, cột, khóa chính và khóa ngoại.", "Thiết kế bảng học viên và khóa học."], ["SELECT & WHERE", "Chọn cột và lọc bản ghi theo điều kiện.", "Lấy các khóa học đang mở và sắp xếp theo tên."]]),
      stage("Aggregation", [["GROUP BY", "Tổng hợp dữ liệu theo nhóm bằng COUNT, SUM và AVG.", "Đếm số đăng ký theo từng khóa học."], ["NULL & dữ liệu thiếu", "Phân biệt giá trị thiếu với chuỗi rỗng và số 0.", "So sánh COUNT(*) và COUNT(cột) khi có NULL."]]),
      stage("Relationships", [["JOIN", "Kết nối bảng và hiểu vì sao số dòng có thể tăng.", "Liệt kê mọi khóa học, kể cả khóa chưa có học viên."], ["Subquery & CTE", "Chia truy vấn thành các bước dễ đọc và kiểm tra.", "Tìm những khóa có số đăng ký cao hơn trung bình."]]),
      stage("Safe writes", [["INSERT, UPDATE, DELETE", "Thay đổi dữ liệu có điều kiện và kiểm tra phạm vi tác động.", "Thử cập nhật trong transaction rồi rollback."], ["Ràng buộc & transaction", "Giữ tính nhất quán khi có nhiều thao tác liên quan.", "Ngăn đăng ký trùng và mô phỏng thao tác thất bại."]]),
      stage("Query quality", [["Index & EXPLAIN", "Đọc kế hoạch truy vấn trước khi chọn chỉ mục.", "So sánh truy vấn có và không có index trên dữ liệu thử."], ["Dự án báo cáo", "Tạo truy vấn tổng hợp với định nghĩa chỉ số rõ ràng.", "Lập báo cáo số đăng ký theo tháng, kiểm tra tránh đếm trùng."]]),
    ] },
];
const extensions: Record<string, RoadmapStage[]> = {
  frontend: [stage('Typed frontend', [['TypeScript & hợp đồng dữ liệu', 'Phân biệt kiểm tra kiểu lúc build và kiểm tra dữ liệu lúc chạy; mô tả response API bằng type.', 'Định nghĩa Course; xử lý response thiếu title mà không làm giao diện vỡ.'], ['Hiệu năng & ảnh', 'Đo layout shift, kích thước tài nguyên và chi phí render trước khi tối ưu.', 'Đặt kích thước ảnh, lazy-load ảnh ngoài màn hình; ghi lại số đo trước và sau.']]), stage('Portfolio review', [['Kiểm tra trải nghiệm', 'Kiểm tra luồng bằng bàn phím, màn hình nhỏ và mạng chậm.', 'Nhờ một người tìm khóa rồi mở chi tiết; ghi ba điểm gây nhầm và sửa lại.'], ['Case study & bàn giao', 'Giải thích quyết định kỹ thuật bằng bằng chứng, không chỉ ảnh đẹp.', 'Viết README có demo, hướng dẫn chạy, test và các giới hạn chưa xử lý.']])],
  backend: [stage('Scaling basics', [['Index & truy vấn chậm', 'Tìm truy vấn tốn thời gian, đo với dữ liệu đại diện và đặt index theo kiểu truy cập.', 'Dùng EXPLAIN cho truy vấn danh sách đăng ký; giải thích index đã chọn.'], ['Đồng thời & idempotency', 'Giữ dữ liệu đúng khi một yêu cầu được gửi lại hoặc nhiều yêu cầu đến cùng lúc.', 'Gửi hai yêu cầu đăng ký song song; đảm bảo chỉ tạo một đăng ký và một phần thưởng.']]), stage('Service operations', [['Health check & timeout', 'Phân biệt dịch vụ còn chạy với dịch vụ có thể phục vụ request; giới hạn thời gian phụ thuộc.', 'Mô phỏng DB không kết nối được và kiểm tra health endpoint không báo khỏe sai.'], ['Backup & rollback', 'Chuẩn bị khôi phục dữ liệu và phiên bản ứng dụng trước khi sự cố xảy ra.', 'Khôi phục backup vào database thử và đối chiếu số bản ghi; ghi các bước rollback.']])],
  python: [stage('Command line tools', [['CLI với argparse', 'Thiết kế tham số dòng lệnh có mặc định, trợ giúp và lỗi dễ hiểu.', 'Thêm --input, --output và --help vào công cụ tổng hợp CSV.'], ['Module & dependency', 'Tổ chức mã theo trách nhiệm và dùng môi trường riêng cho từng dự án.', 'Tách reader, report, cli; cài lại từ môi trường mới mà không phụ thuộc máy cũ.']]), stage('Share your tool', [['Kiểm thử tích hợp CLI', 'Kiểm tra một lượt chạy thực tế với file đầu vào và đầu ra tạm.', 'Dùng dữ liệu mẫu để xác nhận tổng đúng; file đầu vào phải không đổi sau chạy.'], ['Tài liệu & dữ liệu an toàn', 'Viết hướng dẫn sử dụng và tránh đưa bí mật, thông tin cá nhân vào repo.', 'Thêm ví dụ nhỏ giả lập, README và danh sách file không được commit.']])],
  sql: [stage('Analytical SQL', [['Window functions', 'Tính toán theo nhóm mà vẫn giữ chi tiết từng hàng.', 'Xếp hạng khóa theo số đăng ký; so sánh RANK và DENSE_RANK khi bằng nhau.'], ['Running totals', 'Tính tổng lũy kế với thứ tự và window frame rõ ràng.', 'Tổng hợp đăng ký theo ngày rồi tính lũy kế; đối chiếu ngày cuối với tổng toàn kỳ.']]), stage('Trustworthy reports', [['Kiểm tra trùng & thiếu', 'Xác định khóa nghiệp vụ; đo tỷ lệ thiếu và xem JOIN có làm nhân bản dữ liệu.', 'Viết truy vấn phát hiện đăng ký trùng và khóa học không có dòng liên quan.'], ['Định nghĩa & tái lập', 'Ghi rõ một chỉ số đếm ai, trong thời gian nào và trên phiên bản dữ liệu nào.', 'Bàn giao báo cáo kèm định nghĩa người học hoạt động, timezone và bộ dữ liệu đối chiếu.']])],
};
// Existing node IDs remain unchanged so saved learner progress survives expansion.
export const roadmaps: LearningRoadmap[] = foundationRoadmaps.map(roadmap => ({ ...roadmap, stages: [...roadmap.stages, ...(extensions[roadmap.slug] ?? [])] }));
export const findRoadmap = (slug: string) => roadmaps.find(item => item.slug === slug);
export const roadmapNodes = (roadmap: LearningRoadmap) => roadmap.stages.flatMap(stage => stage.nodes);
