export type RoadmapGuide = { audience: string; prerequisite: string; project: string; deliverables: string[]; stages: { label: string; focus: string; checkpoint: string; resources: { title: string; href: string }[] }[] };
const mdn = { title: 'MDN · Học phát triển web', href: 'https://developer.mozilla.org/en-US/docs/Learn_web_development' };
const react = { title: 'React · Tài liệu chính thức', href: 'https://react.dev/learn' };
const node = { title: 'Node.js · Hướng dẫn nền tảng', href: 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs' };
const python = { title: 'Python · Tutorial', href: 'https://docs.python.org/3/tutorial/' };
const sql = { title: 'PostgreSQL · Tutorial', href: 'https://www.postgresql.org/docs/current/tutorial.html' };
const git = { title: 'Pro Git · Sách miễn phí', href: 'https://git-scm.com/book/en/v2' };
export const roadmapGuides: Record<string, RoadmapGuide> = {
  frontend: { audience: 'Bạn thích tạo ra những giao diện có thể nhìn thấy và tương tác.', prerequisite: 'Bắt đầu từ số 0. Cần máy tính, trình duyệt và trình soạn thảo.', project: 'Xây thư viện khóa học của riêng bạn', deliverables: ['Trang danh sách và chi tiết, tìm kiếm theo từ khóa.', 'Giao diện dùng được ở 390px và bằng bàn phím.', 'Có trạng thái tải, lỗi, rỗng và README hướng dẫn chạy.'], stages: [
    { label: 'Hiểu nền tảng web', focus: 'Đi từ địa chỉ URL tới trang được hiển thị. Phân biệt nội dung HTML với cách trình bày CSS.', checkpoint: 'Giải thích một request trong Network; trang có đúng một h1, label cho input và liên kết hoạt động.', resources: [mdn] },
    { label: 'Dựng giao diện', focus: 'Nắm box model trước Flexbox/Grid. Thiết kế từ màn hình nhỏ và kiểm tra độ tương phản.', checkpoint: 'Không cuộn ngang ở 390px; focus nhìn thấy được; nội dung vẫn đọc được khi tăng cỡ chữ.', resources: [mdn] },
    { label: 'Tạo tương tác', focus: 'Thực hành hàm thuần, map/filter, event và Promise; tách dữ liệu khỏi DOM.', checkpoint: 'Bộ lọc xử lý chuỗi rỗng, không có kết quả và lỗi mạng; không chèn HTML từ đầu vào người dùng.', resources: [mdn] },
    { label: 'Tư duy component', focus: 'Thiết kế props, đặt state đúng nơi và tránh lưu state có thể tính từ dữ liệu khác.', checkpoint: 'Component tái sử dụng được; mỗi danh sách có key ổn định; refresh URL chi tiết vẫn mở đúng nội dung.', resources: [react] },
    { label: 'Đưa sản phẩm lên mạng', focus: 'Chia commit có ý nghĩa, kiểm thử luồng chính và ghi rõ cách cài đặt.', checkpoint: 'Một người khác clone repo và chạy được bằng README; kiểm thử tìm kiếm qua cả trường hợp đúng và rỗng.', resources: [git, react] },
    { label: 'TypeScript & chất lượng', focus: 'Mô tả dữ liệu bằng type, kiểm tra API ở runtime và đo trước khi tối ưu.', checkpoint: 'Không dùng any để bỏ qua lỗi; ảnh không làm xê dịch layout; API sai dữ liệu có màn hình lỗi rõ ràng.', resources: [react, mdn] },
    { label: 'Hoàn thiện portfolio', focus: 'Viết case study ngắn: bài toán, quyết định thiết kế, giới hạn và hướng phát triển.', checkpoint: 'Có link demo, ảnh chụp mobile và danh sách giới hạn thật; nhờ một người dùng thử luồng hoàn chỉnh.', resources: [git, mdn] },
  ]},
  backend: { audience: 'Bạn thích logic, dữ liệu và cách hệ thống hoạt động phía sau giao diện.', prerequisite: 'Biết biến, hàm, vòng lặp; làm quen JavaScript trước khi học server.', project: 'Xây API quản lý đăng ký khóa học', deliverables: ['API khóa học, đăng ký học và tiến độ theo từng tài khoản.', 'Validation, phân quyền và lỗi nhất quán.', 'Test tích hợp, tài liệu endpoint và phương án sao lưu.'], stages: [
    { label: 'Request tới response', focus: 'Phân biệt GET/POST/PATCH/DELETE, status và header; hiểu async không đồng nghĩa với chạy CPU song song.', checkpoint: 'API trả JSON và status phù hợp; lỗi đọc dữ liệu không làm treo request.', resources: [node, mdn] },
    { label: 'Thiết kế dữ liệu', focus: 'Vẽ quan hệ học viên–khóa học–đăng ký; đặt khóa và ràng buộc trước khi thêm tính năng.', checkpoint: 'Không thể tạo đăng ký trùng; truy vấn chỉ trả các cột cần thiết; không ghép SQL từ chuỗi người dùng.', resources: [sql] },
    { label: 'Xác thực & phân quyền', focus: 'Session đại diện danh tính; quyền sở hữu phải kiểm tra tại từng endpoint, không chỉ ẩn nút.', checkpoint: 'Tài khoản A không đọc/sửa tiến độ của B; đăng xuất vô hiệu hóa phiên cũ.', resources: [node, mdn] },
    { label: 'Xử lý lỗi & lạm dụng', focus: 'Giới hạn body, định nghĩa schema và dùng log có request ID; không ghi token/mật khẩu.', checkpoint: 'Input thiếu/sai/quá dài đều bị từ chối rõ ràng; log không chứa bí mật.', resources: [node] },
    { label: 'Triển khai có kiểm chứng', focus: 'Tách cấu hình môi trường; kiểm thử trước khi deploy và chuẩn bị khôi phục dữ liệu.', checkpoint: 'Test thành công, từ chối quyền và lỗi dữ liệu đều qua; đã thử restore bản sao lưu.', resources: [node, git] },
    { label: 'Hiệu năng & đồng thời', focus: 'Đo truy vấn chậm, thêm index có mục đích và dùng thao tác nguyên tử khi nhiều request cùng sửa.', checkpoint: 'Hai request đăng ký đồng thời không tạo bản ghi trùng; so sánh kế hoạch truy vấn trước/sau index.', resources: [sql, node] },
    { label: 'Vận hành dịch vụ', focus: 'Đặt health check, timeout và quy trình rollback; mô tả giới hạn của phiên bản đầu.', checkpoint: 'Chủ động mô phỏng DB mất kết nối; API trả lỗi kiểm soát được và phục hồi khi DB trở lại.', resources: [node, git] },
  ]},
  python: { audience: 'Bạn muốn học ngôn ngữ đầu tiên hoặc tự động hóa công việc lặp lại.', prerequisite: 'Không cần biết lập trình trước. Cài Python 3 và dùng môi trường riêng.', project: 'Công cụ tổng hợp chi tiêu từ CSV', deliverables: ['Đọc nhiều tệp, kiểm tra cột và dữ liệu thiếu.', 'Xuất báo cáo JSON/CSV theo nhóm chi tiêu.', 'CLI có trợ giúp, test và không ghi đè dữ liệu gốc.'], stages: [
    { label: 'Bắt đầu với Python', focus: 'Chạy script bằng terminal, tạo venv và phân biệt số với chuỗi nhập từ input.', checkpoint: 'Giải thích cách chạy chương trình; từ chối nhiệt độ nhập không phải số.', resources: [python] },
    { label: 'Điều khiển chương trình', focus: 'Tách input/output khỏi hàm tính toán; dùng return và định nghĩa rõ điều kiện dừng.', checkpoint: 'Trò đoán số dừng đúng số lượt; hàm xử lý được gọi mà không tự in hoặc hỏi input.', resources: [python] },
    { label: 'Xử lý dữ liệu', focus: 'Chọn list/set/dict phù hợp; đọc file với context manager và UTF-8.', checkpoint: 'Từ trùng được đếm đúng; chương trình khởi động được khi file chưa tồn tại.', resources: [python] },
    { label: 'Viết chương trình tin cậy', focus: 'Bắt exception cụ thể; đọc traceback trước khi sửa; thêm test cho lỗi đã gặp.', checkpoint: 'Test có dữ liệu rỗng và JSON hỏng; lỗi được thông báo mà không mất file gốc.', resources: [python] },
    { label: 'Tự động hóa thực tế', focus: 'Kiểm tra response và dữ liệu trả về; tách đọc file, xử lý và xuất báo cáo.', checkpoint: 'Chạy lại với cùng input cho cùng kết quả; tổng trong báo cáo khớp dữ liệu hợp lệ.', resources: [python] },
    { label: 'CLI & cấu trúc dự án', focus: 'Thêm tham số dòng lệnh, trợ giúp và tổ chức module theo trách nhiệm.', checkpoint: 'Có --help; đường dẫn sai trả lỗi dễ hiểu; chạy test không gọi API ngoài.', resources: [python, git] },
    { label: 'Bàn giao công cụ', focus: 'Ghi phiên bản phụ thuộc, ví dụ đầu vào và cách xử lý dữ liệu nhạy cảm.', checkpoint: 'Người khác chạy được từ môi trường mới; dữ liệu mẫu không chứa thông tin cá nhân thật.', resources: [python, git] },
  ]},
  sql: { audience: 'Bạn muốn đọc dữ liệu, xây báo cáo hoặc thiết kế database cho ứng dụng.', prerequisite: 'Hiểu bảng/hàng/cột; dùng PostgreSQL với database thử nghiệm riêng.', project: 'Báo cáo đăng ký và hoạt động học', deliverables: ['Schema học viên, khóa học và đăng ký có ràng buộc.', 'Truy vấn tổng hợp không nhân đôi số liệu khi JOIN.', 'Giải thích chỉ số, kế hoạch truy vấn và bộ dữ liệu đối chiếu.'], stages: [
    { label: 'Ngôn ngữ của dữ liệu', focus: 'Chọn khóa chính, đặt kiểu dữ liệu và viết truy vấn chọn cột rõ ràng.', checkpoint: 'Mỗi bảng có khóa; dữ liệu mẫu có cả giá trị biên; ORDER BY có tiêu chí phá hòa.', resources: [sql] },
    { label: 'Tổng hợp đúng', focus: 'Xác định mỗi dòng đại diện điều gì trước khi GROUP BY; hiểu NULL không bằng 0.', checkpoint: 'Đối chiếu COUNT(*) và COUNT(cột) bằng bảng có NULL; giải thích vì sao hai kết quả khác nhau.', resources: [sql] },
    { label: 'Kết nối nhiều bảng', focus: 'Theo dõi quan hệ 1–n; kiểm tra số dòng trước/sau JOIN và dùng CTE chia nhỏ truy vấn.', checkpoint: 'Khóa chưa có đăng ký vẫn xuất hiện với số 0; khách có nhiều đơn không bị đếm thành nhiều khách.', resources: [sql] },
    { label: 'Ghi dữ liệu an toàn', focus: 'Kiểm tra WHERE bằng SELECT trước UPDATE/DELETE; gộp thao tác liên quan trong transaction.', checkpoint: 'ROLLBACK khôi phục dữ liệu thử; unique constraint chặn đăng ký trùng.', resources: [sql] },
    { label: 'Đọc hiệu năng', focus: 'Đọc EXPLAIN và phân biệt số hàng dự kiến/thực tế; định nghĩa khoảng thời gian báo cáo.', checkpoint: 'Đối chiếu báo cáo với dữ liệu nhỏ tính tay; nêu rõ timezone và cách tính tháng.', resources: [sql] },
    { label: 'Phân tích nâng cao', focus: 'Dùng window function khi cần giữ từng hàng; phân biệt rank, dense_rank và row_number.', checkpoint: 'Xếp hạng có điểm bằng nhau cho kết quả đúng kỳ vọng; running total xử lý thứ tự ổn định.', resources: [sql] },
    { label: 'Đảm bảo chất lượng', focus: 'Kiểm tra thiếu dữ liệu, trùng khóa và ràng buộc; tài liệu hóa định nghĩa số liệu.', checkpoint: 'Báo cáo kèm truy vấn kiểm tra trùng/thiếu; kết quả lặp lại được trên cùng snapshot.', resources: [sql, git] },
  ]},
};
