// Original teaching outlines; references link to official documentation.
export const teachingTracks = [
  { id: 'data-structures', resource: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections', prerequisite: 'Biến, vòng lặp và hàm JavaScript.', lessons: [
    ['Mảng và phép duyệt', 'Tính tổng và tìm giá trị lớn nhất bằng một lần duyệt.', 'Viết summarize([3,1,4]) trả về {sum:8,max:4}; định nghĩa kết quả cho mảng rỗng.'],
    ['Stack và kiểm tra ngoặc', 'Mô phỏng push/pop; giải thích vì sao ngoặc đóng phải khớp đỉnh stack.', 'Giải bài Ngoặc hợp lệ; thử chuỗi rỗng, ([)] và {[]} .'],
    ['Queue và hàng đợi tác vụ', 'Dùng chỉ số head để tránh shift nhiều lần; so sánh FIFO và LIFO.', 'Xử lý ba tác vụ A,B,C đúng thứ tự; bổ sung tác vụ sau khi lấy A ra.'],
    ['Map và bài toán Two Sum', 'Lưu giá trị đã gặp; so sánh cách O(n²) và O(n).', 'Giải Tổng của hai số; kiểm tra [3,3], target 6 không dùng cùng một vị trí.'],
    ['Mini project: lịch sử thao tác', 'Kết hợp hai stack cho undo/redo; phân biệt trạng thái và thao tác.', 'Thêm A, thêm B, undo, redo; kiểm tra thêm C sau undo xóa lịch sử redo.'],
  ]},
  { id: 'algorithms', resource: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions', prerequisite: 'Hàm, mảng và vòng lặp JavaScript.', lessons: [
    ['Đo độ phức tạp', 'Đếm số phép so sánh thay vì chỉ đo thời gian máy.', 'So sánh tìm cặp số với n=10 và n=100; giải thích vì sao số bước tăng gần 100 lần.'],
    ['Insertion sort', 'Duy trì tiền tố đã sắp xếp và dịch phần tử lớn hơn.', 'Sắp xếp [5,2,2,-1]; ghi lại mảng sau mỗi lượt; không dùng sort.'],
    ['Binary search', 'Giữ bất biến khoảng tìm kiếm; cập nhật biên không bỏ sót phần tử.', 'Tìm 7 trong [1,3,7,9]; trả -1 khi tìm 8; kiểm tra mảng rỗng.'],
    ['Đệ quy và điều kiện dừng', 'Theo dõi call stack và giới hạn đầu vào.', 'Viết factorial cho 0..10; từ chối số âm; so sánh bản vòng lặp.'],
    ['Two pointers', 'Thu hẹp khoảng tìm kiếm trên mảng đã sắp xếp.', 'Tìm cặp tổng 10 trong [1,2,4,6,9]; giải thích điều kiện tăng con trỏ trái.'],
  ]},
  { id: 'python', resource: 'https://docs.python.org/3/tutorial/', prerequisite: 'Không yêu cầu lập trình trước; cài Python 3.', lessons: [
    ['Biến và nhập liệu', 'Phân biệt str, int, float và lỗi chuyển kiểu.', 'Đọc giá tiền và số lượng; tính tổng; xử lý đầu vào không phải số.'],
    ['Hàm và kiểm thử', 'Tách tính toán khỏi input/print để dễ kiểm thử.', 'Viết discount(100,10)=90; dùng assert cho 0%, 100% và phần trăm ngoài khoảng.'],
    ['Quản lý đối tượng', 'Xây class Task với trạng thái hoàn thành và phương thức rõ ràng.', 'Tạo hai Task độc lập; hoàn thành một task không ảnh hưởng task còn lại.'],
    ['Đọc CSV', 'Dùng csv.DictReader và kiểm tra dữ liệu thiếu.', 'Đọc doanh thu từ CSV; tính tổng; báo số dòng có giá trị không hợp lệ.'],
    ['Mini project: sổ chi tiêu', 'Tách lưu trữ, nghiệp vụ và giao diện CLI.', 'Thêm khoản chi, lưu JSON, mở lại chương trình vẫn giữ dữ liệu; xử lý file chưa tồn tại.'],
  ]},
  { id: 'frontend', resource: 'https://developer.mozilla.org/en-US/docs/Learn_web_development', prerequisite: 'Trình duyệt và trình soạn thảo code.', lessons: [
    ['HTML có ngữ nghĩa', 'Dùng header/main/nav và label; thứ bậc heading có ý nghĩa.', 'Tạo trang giới thiệu khóa học; dùng bàn phím đến được mọi liên kết và trường nhập.'],
    ['CSS responsive', 'Grid, Flexbox và breakpoint theo nội dung.', 'Dựng lưới khóa học 1/2/3 cột; kiểm tra 390px không tràn ngang.'],
    ['DOM và trạng thái rỗng', 'Lọc danh sách bằng input event; tránh chèn HTML không tin cậy.', 'Tìm khóa theo tên; khi không có kết quả hiển thị thông báo và nút xóa lọc.'],
    ['React: component và state', 'Tách CourseCard, truyền props và dùng state cho bộ lọc.', 'Chuyển danh sách sang React; key ổn định, bộ lọc cập nhật khi gõ.'],
    ['Mini project: thư viện học tập', 'Kết hợp responsive, loading, error và empty states.', 'Hiển thị dữ liệu từ API; thử mạng lỗi và màn hình nhỏ; kiểm tra label bằng bàn phím.'],
  ]},
  { id: 'sql', resource: 'https://www.postgresql.org/docs/current/tutorial.html', prerequisite: 'Cài PostgreSQL và công cụ truy vấn; biết bảng/hàng/cột.', lessons: [
    ['SELECT và WHERE', 'Chọn cột cụ thể, lọc giá trị và sắp xếp ổn định.', 'Tạo products(id,name,price); lấy sản phẩm giá >=100 theo price rồi id.'],
    ['JOIN và dữ liệu thiếu', 'Phân biệt INNER JOIN và LEFT JOIN bằng khách chưa đặt hàng.', 'Tạo customers và orders; liệt kê mọi khách kể cả khách chưa có đơn.'],
    ['GROUP BY và COUNT', 'Nhóm doanh thu; phân biệt COUNT(*) với COUNT(column).', 'Đếm đơn từng khách bằng LEFT JOIN; khách không có đơn phải nhận 0.'],
    ['Subquery và EXISTS', 'Diễn đạt điều kiện tồn tại mà không nhân bản hàng.', 'Tìm khách có đơn >500; mỗi khách chỉ xuất hiện một lần dù có nhiều đơn.'],
    ['Thiết kế database', 'Khóa chính, khóa ngoại và giao dịch giữ dữ liệu nhất quán.', 'Tạo order_items có khóa ngoại; thử chèn đơn không tồn tại và rollback giao dịch lỗi.'],
  ]},
  { id: 'interview', resource: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map', prerequisite: 'Đã học cấu trúc dữ liệu và thuật toán cơ bản.', lessons: [
    ['Làm rõ đề trước khi code', 'Xác nhận input/output, giới hạn và trường hợp không có đáp án.', 'Trình bày Two Sum trong 5 phút: brute force, Map, test và độ phức tạp.'],
    ['BFS và cây', 'Dùng queue phân tách từng tầng; phân biệt cây rỗng và nút lá.', 'Vẽ cây 1 với con 2,3; mô phỏng queue và xuất [[1],[2,3]].'],
    ['Quy hoạch động', 'Xác định trạng thái, chuyển trạng thái và base case.', 'Đếm cách leo n bậc với bước 1/2; kiểm tra n=0,1,2; tối ưu bộ nhớ.'],
    ['System design nhập môn', 'Xác định nhu cầu, API, dữ liệu và nút thắt; tránh thêm hệ thống chưa cần.', 'Thiết kế dịch vụ rút gọn URL; giải thích xử lý trùng mã và giới hạn request.'],
    ['Mock interview tự đánh giá', 'Phân bổ 5 phút làm rõ, 20 phút giải, 10 phút test, 5 phút tổng kết.', 'Ghi hình một lời giải; tự chấm 4 mục: đúng, rõ ràng, test biên và độ phức tạp.'],
  ]},
];

export const gradedProblems = [
  { id: 3, statement: 'Hai danh sách liên kết được mã hóa bằng hai mảng số đã tăng dần. Viết solve(a,b) trả mảng tăng dần chứa mọi phần tử của cả hai, giữ phần tử trùng. Đây là bài luyện phép trộn; không yêu cầu tạo Node.', starterCode: 'function solve(a,b) {\n  // Trộn hai mảng đã sắp xếp\n}', exampleInput: '[1,2,4], [1,3,4]', exampleOutput: '[1,1,2,3,4,4]', constraints: ['Mỗi mảng 0–1000 số nguyên trong [-10000,10000].', 'Đầu vào tăng không nghiêm ngặt; mục tiêu O(a.length+b.length).'], reference: 'function solve(a,b){let i=0,j=0,r=[];while(i<a.length&&j<b.length)r.push(a[i]<=b[j]?a[i++]:b[j++]);return r.concat(a.slice(i),b.slice(j))}', tests: [{args:[[1,2,4],[1,3,4]],expected:[1,1,2,3,4,4],sample:true},{args:[[],[]],expected:[],sample:false},{args:[[],[1]],expected:[1],sample:false},{args:[[-3,0],[0,2]],expected:[-3,0,0,2],sample:false},{args:[[1,1],[1]],expected:[1,1,1],sample:false}] },
  { id: 4, statement: 'Viết solve(text) trả độ dài chuỗi con liên tiếp dài nhất không lặp ký tự. Chuỗi chỉ gồm ASCII; khoảng trắng cũng là ký tự.', starterCode: 'function solve(text) {\n  // Trả số nguyên\n}', exampleInput: '"abcabcbb"', exampleOutput: '3', constraints: ['0–10000 ký tự ASCII.', 'Chuỗi con phải liên tiếp; chuỗi rỗng trả 0.'], reference: 'function solve(s){let l=0,best=0;const m=new Map();for(let r=0;r<s.length;r++){if(m.has(s[r]))l=Math.max(l,m.get(s[r])+1);m.set(s[r],r);best=Math.max(best,r-l+1)}return best}', tests: [{args:['abcabcbb'],expected:3,sample:true},{args:[''],expected:0,sample:false},{args:['bbbbb'],expected:1,sample:false},{args:['pwwkew'],expected:3,sample:false},{args:['abba'],expected:2,sample:false},{args:['a b c'],expected:3,sample:false}] },
  { id: 6, statement: 'Viết solve(nums,target) tìm chỉ số target trong mảng số nguyên tăng nghiêm ngặt đã xoay vòng 0 hoặc nhiều vị trí. Không tìm thấy trả -1.', starterCode: 'function solve(nums,target) {\n  // Trả chỉ số hoặc -1\n}', exampleInput: '[4,5,6,7,0,1,2], 0', exampleOutput: '4', constraints: ['0–10000 phần tử khác nhau; số nguyên trị tuyệt đối <= 10^9.', 'Mục tiêu O(log n); bộ chấm kiểm tra kết quả, không chứng minh độ phức tạp.'], reference: 'function solve(a,t){let l=0,r=a.length-1;while(l<=r){let m=(l+r)>>1;if(a[m]===t)return m;if(a[l]<=a[m]){if(a[l]<=t&&t<a[m])r=m-1;else l=m+1}else{if(a[m]<t&&t<=a[r])l=m+1;else r=m-1}}return -1}', tests: [{args:[[4,5,6,7,0,1,2],0],expected:4,sample:true},{args:[[],1],expected:-1,sample:false},{args:[[1],1],expected:0,sample:false},{args:[[1,2,3],3],expected:2,sample:false},{args:[[3,1,2],4],expected:-1,sample:false},{args:[[3,1,2],3],expected:0,sample:false}] },
  { id: 7, statement: 'Viết solve(tree) trả các tầng của cây nhị phân. Đầu vào dùng biểu diễn heap: nút i có con trái 2*i+1 và con phải 2*i+2; null là không có nút. Không có nút con dưới nút null. Cây rỗng trả [].', starterCode: 'function solve(tree) {\n  // Trả mảng các tầng\n}', exampleInput: '[1,2,3,null,5]', exampleOutput: '[[1],[2,3],[5]]', constraints: ['0–1023 vị trí; mỗi giá trị là số nguyên hoặc null.', 'Đây là chỉ số heap, không phải định dạng bỏ qua các ô con của null.'], reference: 'function solve(a){const r=[];for(let i=0;i<a.length;i++){if(a[i]!==null){const d=Math.floor(Math.log2(i+1));(r[d]??=[]).push(a[i])}}return r.filter(Boolean)}', tests: [{args:[[1,2,3,null,5]],expected:[[1],[2,3],[5]],sample:true},{args:[[]],expected:[],sample:false},{args:[[null]],expected:[],sample:false},{args:[[8]],expected:[[8]],sample:false},{args:[[1,null,3,null,null,6,7]],expected:[[1],[3],[6,7]],sample:false}] },
  { id: 8, statement: 'Viết solve(n) đảo các chữ số thập phân, giữ dấu. Trả 0 nếu kết quả nằm ngoài khoảng số nguyên có dấu 32 bit [-2147483648,2147483647]. Bỏ số 0 ở đầu kết quả.', starterCode: 'function solve(n) {\n  // Trả số nguyên sau khi đảo\n}', exampleInput: '-120', exampleOutput: '-21', constraints: ['n là số nguyên có dấu 32 bit.', 'Đầu vào 0 trả 0.'], reference: 'function solve(n){const r=Math.sign(n)*Number(String(Math.abs(n)).split("").reverse().join(""));return r < -2147483648 || r > 2147483647 ? 0 : r===0?0:r}', tests: [{args:[-120],expected:-21,sample:true},{args:[0],expected:0,sample:false},{args:[123],expected:321,sample:false},{args:[1534236469],expected:0,sample:false},{args:[-2147483648],expected:0,sample:false},{args:[1463847412],expected:2147483641,sample:false}] },
  { id: 9, statement: 'Viết solve(grid) trả số bước ít nhất từ góc trên trái đến góc dưới phải. Ô 0 đi được, 1 là tường. Mỗi bước đi lên/xuống/trái/phải. Không có đường hoặc hai đầu là tường trả -1. Một ô trống duy nhất cần 0 bước.', starterCode: 'function solve(grid) {\n  // BFS; trả số bước hoặc -1\n}', exampleInput: '[[0,0],[1,0]]', exampleOutput: '2', constraints: ['Lưới chữ nhật 1–50 hàng và 1–50 cột.', 'Đếm bước đi (cạnh), không đếm số ô.'], reference: 'function solve(g){let n=g.length,m=g[0].length;if(g[0][0]||g[n-1][m-1])return -1;let q=[[0,0,0]],seen=new Set(["0,0"]);for(let h=0;h<q.length;h++){let [r,c,d]=q[h];if(r===n-1&&c===m-1)return d;for(let [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){let x=r+dr,y=c+dc,k=x+","+y;if(x>=0&&x<n&&y>=0&&y<m&&!g[x][y]&&!seen.has(k)){seen.add(k);q.push([x,y,d+1])}}}return -1}', tests: [{args:[[[0,0],[1,0]]],expected:2,sample:true},{args:[[[0]]],expected:0,sample:false},{args:[[[1]]],expected:-1,sample:false},{args:[[[0,1],[1,0]]],expected:-1,sample:false},{args:[[[0,0,0],[1,1,0],[0,0,0]]],expected:4,sample:false},{args:[[[0,0,1]]],expected:-1,sample:false}] },
  { id: 10, statement: 'Viết solve(nums) trả độ dài dãy con tăng nghiêm ngặt dài nhất. Được bỏ phần tử nhưng phải giữ thứ tự ban đầu; dãy con không cần liên tiếp.', starterCode: 'function solve(nums) {\n  // Trả độ dài LIS\n}', exampleInput: '[10,9,2,5,3,7,101,18]', exampleOutput: '4', constraints: ['0–1000 số nguyên trị tuyệt đối <= 10000.', 'Các phần tử bằng nhau không làm tăng độ dài.'], reference: 'function solve(a){const d=a.map(()=>1);let best=0;for(let i=0;i<a.length;i++){for(let j=0;j<i;j++)if(a[j]<a[i])d[i]=Math.max(d[i],d[j]+1);best=Math.max(best,d[i])}return best}', tests: [{args:[[10,9,2,5,3,7,101,18]],expected:4,sample:true},{args:[[]],expected:0,sample:false},{args:[[2,2,2]],expected:1,sample:false},{args:[[5,4,3]],expected:1,sample:false},{args:[[-2,-1,0]],expected:3,sample:false},{args:[[3,1,2,4]],expected:3,sample:false}] },
  { id: 11, statement: 'Viết solve(lists) trộn K danh sách tăng dần thành một mảng tăng dần. Mỗi danh sách liên kết được biểu diễn bằng mảng số; giữ mọi phần tử trùng.', starterCode: 'function solve(lists) {\n  // Trả mảng đã hợp nhất\n}', exampleInput: '[[1,4],[1,3],[]]', exampleOutput: '[1,1,3,4]', constraints: ['0–100 danh sách; tổng tối đa 10000 số nguyên.', 'Mục tiêu dùng min-heap O(N log K); bộ test chỉ kiểm tra kết quả.'], reference: 'function solve(lists){return lists.flat().sort((a,b)=>a-b)}', tests: [{args:[[[1,4],[1,3],[]]],expected:[1,1,3,4],sample:true},{args:[[]],expected:[],sample:false},{args:[[[],[]]],expected:[],sample:false},{args:[[[-3,-1],[0,2]]],expected:[-3,-1,0,2],sample:false},{args:[[[2],[2],[2]]],expected:[2,2,2],sample:false}] },
  { id: 12, statement: 'Viết solve(nums) đếm cặp chỉ số i<j sao cho nums[i]>nums[j]. Hai giá trị bằng nhau không tạo nghịch thế. Trả số nguyên, không phải mảng đã sắp xếp.', starterCode: 'function solve(nums) {\n  // Đếm nghịch thế\n}', exampleInput: '[2,4,1,3,5]', exampleOutput: '3', constraints: ['0–1000 số nguyên trị tuyệt đối <= 10000.', 'Mục tiêu O(n log n) với merge sort; bộ chấm kiểm tra tính đúng.'], reference: 'function solve(a){let n=0;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)if(a[i]>a[j])n++;return n}', tests: [{args:[[2,4,1,3,5]],expected:3,sample:true},{args:[[]],expected:0,sample:false},{args:[[3,2,1]],expected:3,sample:false},{args:[[1,1,1]],expected:0,sample:false},{args:[[1,2,3]],expected:0,sample:false},{args:[[-1,-3,-2]],expected:2,sample:false}] },
  { id: 1, statement: 'Viết solve(nums, target), trả về hai chỉ số tăng dần có tổng giá trị bằng target. Mỗi đầu vào có đúng một cặp; không dùng lại một vị trí.', starterCode: 'function solve(nums, target) {\n  // Trả về [i, j] với i < j\n}', exampleInput: '[2,7,11,15], 9', exampleOutput: '[0,1]', constraints: ['2–10000 số nguyên; trị tuyệt đối <= 10^9.', 'Đúng một cặp; kết quả [i,j] theo thứ tự tăng.'], reference: 'function solve(a,t){const m=new Map();for(let i=0;i<a.length;i++){if(m.has(t-a[i]))return [m.get(t-a[i]),i];m.set(a[i],i)}}', tests: [ {args:[[2,7,11,15],9],expected:[0,1],sample:true}, {args:[[3,3],6],expected:[0,1],sample:false}, {args:[[-3,4,3,90],0],expected:[0,2],sample:false}, {args:[[0,4,3,0],0],expected:[0,3],sample:false}, {args:[[1,2,8,6],14],expected:[2,3],sample:false} ] },
  { id: 2, statement: 'Viết solve(text) trả boolean. Chỉ giữ chữ cái ASCII a–z/A–Z và chữ số 0–9, không phân biệt hoa thường; chuỗi còn lại đọc xuôi/ngược giống nhau là đối xứng. Chuỗi rỗng là true.', starterCode: 'function solve(text) {\n  // Trả về boolean\n}', exampleInput: '"A man, a plan, a canal: Panama"', exampleOutput: 'true', constraints: ['0–10000 ký tự ASCII.', 'Bỏ mọi ký tự không phải chữ cái hoặc chữ số.'], reference: 'function solve(s){s=s.toLowerCase().replace(/[^a-z0-9]/g,"");return s===s.split("").reverse().join("")}', tests: [{args:['A man, a plan, a canal: Panama'],expected:true,sample:true},{args:['race a car'],expected:false,sample:false},{args:[''],expected:true,sample:false},{args:['0P'],expected:false,sample:false},{args:['.,'],expected:true,sample:false},{args:['abba'],expected:true,sample:false}] },
  { id: 5, statement: 'Viết solve(text) trả boolean xác định chuỗi ngoặc (), [], {} đóng mở đúng thứ tự. Chuỗi rỗng hợp lệ. Mọi ký tự đều là một trong sáu ký tự ngoặc.', starterCode: 'function solve(text) {\n  // Dùng stack và trả về boolean\n}', exampleInput: '"{[]}"', exampleOutput: 'true', constraints: ['0–10000 ký tự ngoặc.', 'Phải đóng đúng loại và đúng thứ tự lồng nhau.'], reference: 'function solve(s){const stack=[],pairs={")":"(","]":"[","}":"{"};for(const c of s){if("([{ ".trim().includes(c))stack.push(c);else if(stack.pop()!==pairs[c])return false}return stack.length===0}', tests: [{args:['{[]}'],expected:true,sample:true},{args:['([)]'],expected:false,sample:false},{args:[''],expected:true,sample:false},{args:['('],expected:false,sample:false},{args:[')('],expected:false,sample:false},{args:['()[]{}'],expected:true,sample:false}] },
];
