import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowUpRight} from 'lucide-react';
import EduPublicShell from '@/app/edu-public-shell';
import ActivityHero,{ActivityConnections} from '@/app/edu-activity-hero';
import {eduActivities} from '@/lib/edu-activities';
export function generateStaticParams(){return eduActivities.map(a=>({slug:a.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=eduActivities.find(a=>a.slug===slug);return {title:a?`${a.title} — DolphinX Edu`:'Không tìm thấy hoạt động'};}
export default async function Activity({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=eduActivities.find(a=>a.slug===slug);if(!a)notFound();return <EduPublicShell><ActivityHero slug={slug} title={a.title} category={a.category} href={a.href} cta={a.cta}/><section className="edu-container ed-activity-detail"><article data-reveal><p className="ed-lead">{a.intro}</p><h2>Bắt đầu như thế nào?</h2><ol className="ed-activity-steps">{a.steps.map((step,i)=><li key={step}><span>0{i+1}</span><p>{step}</p></li>)}</ol><h3>Điều bạn mang về</h3><p>{a.result}</p><div className="ed-activity-note"><h3>Một không gian tôn trọng nhau</h3><p>Chia sẻ code và dữ liệu bạn có quyền sử dụng. Không đăng mật khẩu, thông tin cá nhân hoặc đáp án của cuộc thi đang diễn ra. Góp ý vào cách làm, không công kích người học.</p></div></article><aside><span className="edu-label">THÔNG TIN THAM GIA</span><h3>{a.category}</h3><ul className="ed-activity-side-list"><li>Chuẩn bị mục tiêu hoặc câu hỏi cụ thể.</li><li>Thực hành bằng công cụ trực tuyến.</li><li>Ghi lại kết quả và điều cần cải thiện.</li></ul><p>Bạn có thể bắt đầu từ công cụ và khu trao đổi hiện có. Các buổi có mentor hoặc lịch tổ chức riêng cần được đội ngũ xác nhận.</p><Link className="edu-button" href={a.href}>{a.cta}<ArrowUpRight size={18}/></Link><Link className="edu-link" href="/contact">Hỏi về lịch hướng dẫn <ArrowUpRight size={17}/></Link></aside></section><ActivityConnections/><div className="edu-container"><p className="ed-activity-calendar-note">Lịch thi chung của DolphinX Edu, không phải lịch riêng của hoạt động này. Các buổi hướng dẫn cần được đội ngũ xác nhận.</p></div><EduHomeEvents/><section className="edu-container edu-section" data-reveal><div className="edu-section-head"><h2>Thêm một cách<br/>để cùng tiến bộ.</h2><Link className="edu-link" href="/extracurriculars">Xem tất cả <ArrowUpRight size={19}/></Link></div><div className="ed-related">{eduActivities.filter(item=>item.slug!==slug).slice(0,3).map(item=><Link key={item.slug} href={`/extracurriculars/${item.slug}`}>{item.title}<ArrowUpRight size={20}/></Link>)}</div></section></EduPublicShell>}
import EduHomeEvents from '@/app/edu-home-events';
