import Link from 'next/link';
import { redirect } from 'next/navigation';
import { isAdminAuthenticated } from '@/lib/admin-auth';
import { hubDb,pageNumber } from '@/lib/hub';
import AcademyForm from '@/app/academy/form';
import { moderate } from './actions';
import '@/app/academy.css';
import '@/app/public-hub.css';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<{page?:string;status?:string}>}){
 if(!await isAdminAuthenticated())redirect('/admin');const query=await searchParams,page=pageNumber(query.page),status=['pending','published','hidden'].includes(query.status??'')?query.status!:'pending';const db=await hubDb();
 const [posts,comments,reports]=await Promise.all([db.collection('community_posts').find({status}).sort({createdAt:-1}).skip((page-1)*20).limit(21).toArray(),db.collection('community_comments').find({status}).sort({createdAt:-1}).skip((page-1)*20).limit(21).toArray(),db.collection('community_reports').find({status:'open'}).sort({createdAt:-1}).skip((page-1)*20).limit(21).toArray()]);
 return <main className="hub-main academy"><header><Link href="/admin">← Quản trị</Link><Link href="/admin/contests">Quản lý contest →</Link><Link href="/community">Xem cộng đồng ↗</Link></header><h1>Kiểm duyệt cộng đồng</h1><p>Bài viết và bình luận cần duyệt trước khi công khai. Ẩn nội dung là thao tác có thể phục hồi.</p><nav className="hub-tabs">{[['pending','Chờ duyệt'],['published','Công khai'],['hidden','Đã ẩn']].map(([s,t])=><Link key={s} href={`?status=${s}`}>{t}</Link>)}</nav>{[['post',posts,'Bài viết'],['comment',comments,'Bình luận']].map(([kind,items,title])=><section key={String(kind)}><h2>{String(title)}</h2>{(items as typeof posts).slice(0,20).map(item=><article className="hub-card" key={item._id.toString()}><p>{item.authorName} · ID {item.userId}</p><h3>{item.title??'Bình luận'}</h3><p className="hub-body">{item.body}</p><AcademyForm action={moderate} label="Lưu trạng thái"><input type="hidden" name="action" value={String(kind)}/><input type="hidden" name="id" value={item._id.toString()}/><label>Trạng thái<select name="status" defaultValue={item.status}><option value="pending">Chờ duyệt</option><option value="published">Công khai</option><option value="hidden">Ẩn</option></select></label></AcademyForm></article>)}{!(items as typeof posts).length&&<p>Không có nội dung ở trạng thái này.</p>}</section>)}<section><h2>Báo cáo đang mở</h2>{reports.slice(0,20).map(r=><article className="hub-card" key={r._id.toString()}><Link href={`/community/${r.postId}`}>Xem bài liên quan ↗</Link><p>Bài: {r.postId}{r.commentId?` · Bình luận: ${r.commentId}`:''}</p><p className="hub-body">{r.reason}</p><AcademyForm action={moderate} label="Ẩn nội dung bị báo cáo"><input type="hidden" name="action" value={r.commentId?'comment':'post'}/><input type="hidden" name="id" value={r.commentId||r.postId}/><input type="hidden" name="status" value="hidden"/></AcademyForm><AcademyForm action={moderate} label="Đánh dấu đã xử lý"><input type="hidden" name="action" value="resolve"/><input type="hidden" name="id" value={r._id.toString()}/></AcademyForm></article>)}{!reports.length&&<p>Không có báo cáo đang mở.</p>}</section><nav className="hub-pagination">{page>1&&<Link href={`?status=${status}&page=${page-1}`}>← Trước</Link>}<span>Trang {page}</span>{[posts,comments,reports].some(items=>items.length>20)&&<Link href={`?status=${status}&page=${page+1}`}>Tiếp →</Link>}</nav><section className="hub-card"><h2>Quyền tương tác cộng đồng</h2><AcademyForm action={moderate} label="Cập nhật quyền"><input type="hidden" name="action" value="block"/><label>ID học viên<input name="id" required pattern="[a-fA-F0-9]{24}"/></label><label>Quyền<select name="blocked"><option value="true">Hạn chế đăng bài, thích, bình luận</option><option value="false">Khôi phục tương tác</option></select></label></AcademyForm></section></main>;
}
