import Link from 'next/link';
import { redirect } from 'next/navigation';
import { isAdminAuthenticated } from '@/lib/admin-auth';
import { getMongoDatabase } from '@/lib/mongodb';
import AcademyForm from '@/app/academy/form';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { manageTeaching } from './actions';
import '../../academy.css';
export const dynamic = 'force-dynamic';
export default async function JudgeAdmin() {
  if (!await isAdminAuthenticated()) redirect('/admin');
  const db = await getMongoDatabase();
  const [problems, configs, submissions] = await Promise.all([db.collection('problems').find().sort({ id: 1 }).toArray(), db.collection('judge_configs').find().toArray(), db.collection('submissions').find({}, { projection: { code: 0 } }).sort({ createdAt: -1 }).limit(30).toArray()]);
  return <main className="academy academy-admin"><header><Link href="/admin">← Quản trị</Link><Link href="/admin/academy">Giáo án & video →</Link></header><h1>Máy chấm & tài nguyên học</h1><p>JavaScript đồng bộ · 250 ms/test · 16 MB heap QuickJS · tối đa 30 test. Chạy mẫu không cộng XP. Nộp đúng lần đầu được 30 XP.</p><Card><CardHeader><CardTitle>Nhập chương trình khởi đầu</CardTitle></CardHeader><CardContent><p>6 khóa × 5 giáo án, video demo và 12 bài có đề và test chuẩn, bao gồm mảng, chuỗi, cây, đồ thị và quy hoạch động.</p><AcademyForm action={manageTeaching} label="Nhập / kiểm tra nội dung mẫu"><input type="hidden" name="action" value="seed"/></AcademyForm></CardContent></Card><Card><CardHeader><CardTitle>Kho bài tập mở rộng</CardTitle></CardHeader><CardContent><p>10 bài tình huống thực tế: cửa sổ trượt, tìm kiếm, stack, tham lam, đồ thị và quy hoạch động. Kiểm chứng lời giải trước khi nhập; không ghi đè nội dung đã sửa.</p><AcademyForm action={manageTeaching} label="Nhập / kiểm tra 10 bài mở rộng"><input type="hidden" name="action" value="expand"/></AcademyForm></CardContent></Card>{problems.map(p => { const config = configs.find(c => c.problemId === p.id); return <Card key={p.id}><CardHeader><CardTitle>{p.id}. {p.title} · {config?.enabled ? 'Đang chấm' : 'Chưa bật'}</CardTitle></CardHeader><CardContent>{config?.enabled && <AcademyForm action={manageTeaching} label="Tạm ngưng chấm bài này"><input type="hidden" name="action" value="disable"/><input type="hidden" name="problemId" value={p.id}/></AcademyForm>}<details><summary>Quản lý test và lời giải chuẩn</summary><p>JSON: mỗi test có args (mảng tham số truyền vào solve), expected (JSON), sample (true/false). Ít nhất 1 test mẫu và 1 test ẩn. Test ẩn không gửi về học viên; kết quả chỉ trả số test đạt. Khi sửa đề, hãy cập nhật đồng thời bộ test.</p><AcademyForm action={manageTeaching} label="Kiểm chứng & lưu"><input type="hidden" name="action" value="save"/><input type="hidden" name="problemId" value={p.id}/><label>Test cases<textarea name="tests" rows={12} required maxLength={50000} defaultValue={JSON.stringify(config?.tests ?? [{ args: [1], expected: 1, sample: true }, { args: [2], expected: 2, sample: false }], null, 2)}/></label><label>Lời giải chuẩn (chỉ admin)<textarea name="reference" required rows={7} maxLength={20000} defaultValue={config?.reference ?? ''}/></label><label><input type="checkbox" name="enabled" defaultChecked={config?.enabled ?? false}/> Bật chấm sau khi lời giải chuẩn qua test</label></AcademyForm></details></CardContent></Card>; })}<Card><CardHeader><CardTitle>30 lượt nộp gần nhất</CardTitle></CardHeader><CardContent>{submissions.map(s => <p key={s._id.toString()}>Bài #{s.problemId} · {s.accepted ? 'Đạt' : 'Chưa đạt'} · {s.runtimeMs} ms · {new Date(s.createdAt).toLocaleString('vi-VN')} · Học viên {String(s.learnerId)}</p>)}</CardContent></Card></main>;
}
